// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/bootstrap.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EndpointSchema is a full data description of one endpoint, registered
// by the customer's stub at startup so gist-server can serve, validate,
// and document it without ever seeing the customer's Go types.
type EndpointSchema struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method         string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path           string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Tags           []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Deprecated     bool                   `protobuf:"varint,7,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	SecurityScheme string                 `protobuf:"bytes,8,opt,name=security_scheme,json=securityScheme,proto3" json:"security_scheme,omitempty"`
	Fields         []*Field               `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty"`
	OutputFields   []*Field               `protobuf:"bytes,10,rep,name=output_fields,json=outputFields,proto3" json:"output_fields,omitempty"`
	Mock           []byte                 `protobuf:"bytes,11,opt,name=mock,proto3" json:"mock,omitempty"` // JSON, optional
	ExpectedErrors []*ExpectedError       `protobuf:"bytes,12,rep,name=expected_errors,json=expectedErrors,proto3" json:"expected_errors,omitempty"`
	// content_type overrides the response's Content-Type header and, when
	// set, tells gist-server to write the handler's output bytes verbatim
	// instead of assuming they're a JSON-encoded struct - see
	// gistapiserver.RawEndpointHandler, the one thing that sets this.
	// Empty (the default) keeps the existing "application/json" behavior.
	ContentType   string `protobuf:"bytes,13,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointSchema) Reset() {
	*x = EndpointSchema{}
	mi := &file_proto_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSchema) ProtoMessage() {}

func (x *EndpointSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSchema.ProtoReflect.Descriptor instead.
func (*EndpointSchema) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointSchema) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EndpointSchema) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EndpointSchema) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EndpointSchema) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EndpointSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EndpointSchema) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EndpointSchema) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *EndpointSchema) GetSecurityScheme() string {
	if x != nil {
		return x.SecurityScheme
	}
	return ""
}

func (x *EndpointSchema) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *EndpointSchema) GetOutputFields() []*Field {
	if x != nil {
		return x.OutputFields
	}
	return nil
}

func (x *EndpointSchema) GetMock() []byte {
	if x != nil {
		return x.Mock
	}
	return nil
}

func (x *EndpointSchema) GetExpectedErrors() []*ExpectedError {
	if x != nil {
		return x.ExpectedErrors
	}
	return nil
}

func (x *EndpointSchema) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// HandshakeRequest carries the connecting SDK's own resolved version -
// sent once, right after the admin channel becomes ready and before any
// Register/GenerateFixtures call, so a version mismatch is caught at
// connect time instead of surfacing as a confusing failure somewhere
// downstream. sdk_version is read from the customer's compiled binary's
// own embedded build info (see gist's sdkVersion()), not a compile-time
// constant, so it reflects what's actually running even across a
// replace-driven local build - empty when that can't be determined, in
// which case gist-server skips the check rather than guessing.
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SdkVersion    string                 `protobuf:"bytes,1,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_proto_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_proto_bootstrap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{2}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// service_id is the config.json gist-api entry's own "id" - gist-server
	// hosts one independent public listener + registry per enabled entry,
	// so registration must say which one this endpoint belongs to.
	ServiceId     string          `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Schema        *EndpointSchema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_bootstrap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterRequest) GetSchema() *EndpointSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_bootstrap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{4}
}

// RegisterMiddlewareRequest tracks that a named middleware (see
// callback.proto's InvokeMiddlewareRequest) now has a real callback
// registered for it - the same "declare the schema so gist-server knows
// it exists" step Register does for an endpoint, but for a middleware
// name instead. Tracked per service_id, mirroring Register's own
// per-instance schema registry.
type RegisterMiddlewareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMiddlewareRequest) Reset() {
	*x = RegisterMiddlewareRequest{}
	mi := &file_proto_bootstrap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMiddlewareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMiddlewareRequest) ProtoMessage() {}

func (x *RegisterMiddlewareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMiddlewareRequest.ProtoReflect.Descriptor instead.
func (*RegisterMiddlewareRequest) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterMiddlewareRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterMiddlewareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterMiddlewareAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMiddlewareAck) Reset() {
	*x = RegisterMiddlewareAck{}
	mi := &file_proto_bootstrap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMiddlewareAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMiddlewareAck) ProtoMessage() {}

func (x *RegisterMiddlewareAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMiddlewareAck.ProtoReflect.Descriptor instead.
func (*RegisterMiddlewareAck) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{6}
}

// ValidateMiddlewaresRequest is called once, at the end of the
// customer's own gist.NewApp(...).Run() - after every Attach/
// AttachMiddlewares Option has already run its own registration RPCs -
// to fail the customer's own process to start (not gist-server's) if
// any endpoint's configured middleware name was never registered.
// gist-server's own PostBuild can't validate this itself: it runs
// during gist-server's own startup, strictly before the customer's SDK
// process has even connected, so there's nothing yet to check against.
// No service_id: this checks every enabled gist-api-server instance at
// once, since the SDK has no reason to separately track which instance
// IDs a given process happened to Attach/AttachMiddlewares to.
type ValidateMiddlewaresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMiddlewaresRequest) Reset() {
	*x = ValidateMiddlewaresRequest{}
	mi := &file_proto_bootstrap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMiddlewaresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMiddlewaresRequest) ProtoMessage() {}

func (x *ValidateMiddlewaresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMiddlewaresRequest.ProtoReflect.Descriptor instead.
func (*ValidateMiddlewaresRequest) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{7}
}

type ValidateMiddlewaresResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// missing is one pre-formatted, human-readable description per
	// configured-but-never-registered middleware name (e.g. service
	// "reaction-api" endpoint "get-thing": middleware "my-auth" never
	// registered) - a plain string rather than a structured message,
	// since the only consumer is Run()'s own fatal error text.
	Missing       []string `protobuf:"bytes,1,rep,name=missing,proto3" json:"missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMiddlewaresResponse) Reset() {
	*x = ValidateMiddlewaresResponse{}
	mi := &file_proto_bootstrap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMiddlewaresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMiddlewaresResponse) ProtoMessage() {}

func (x *ValidateMiddlewaresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMiddlewaresResponse.ProtoReflect.Descriptor instead.
func (*ValidateMiddlewaresResponse) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateMiddlewaresResponse) GetMissing() []string {
	if x != nil {
		return x.Missing
	}
	return nil
}

// ColumnKinds is one table's column -> Go kind ("int"/"float"/"bool"/
// "string"/"other"), reflected client-side at the same time as
// rows_json - a plain JSON round-trip loses the int-vs-float64
// distinction entirely (encoding/json decodes every JSON number as
// float64, and Go's own encoder renders a whole float64 identically to
// an int - e.g. both 5 and 5.0 marshal to "5"), so gist-server's schema
// generator can't reconstruct it from rows_json alone. This is real
// type information only reflection (client-side, before it ever
// touches JSON) can provide.
type ColumnKinds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         map[string]string      `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnKinds) Reset() {
	*x = ColumnKinds{}
	mi := &file_proto_bootstrap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnKinds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnKinds) ProtoMessage() {}

func (x *ColumnKinds) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnKinds.ProtoReflect.Descriptor instead.
func (*ColumnKinds) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{9}
}

func (x *ColumnKinds) GetKinds() map[string]string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

// GenerateFixturesRequest carries the customer's already-reflected fixture
// rows (mirrors plugins/services/gist_fixtures.GenerateFixtures(id,
// rows...): reflecting the customer's tagged model values into table-name
// -> records is mechanical, done client-side; rows_json is that collected
// map[string][]map[string]any, JSON-encoded. Building the actual SQL/JS
// init script from it is not mechanical and stays server-side.
type GenerateFixturesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ServiceId     string                  `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	RowsJson      []byte                  `protobuf:"bytes,2,opt,name=rows_json,json=rowsJson,proto3" json:"rows_json,omitempty"`
	ColumnKinds   map[string]*ColumnKinds `protobuf:"bytes,3,rep,name=column_kinds,json=columnKinds,proto3" json:"column_kinds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // table name -> its columns' real kinds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFixturesRequest) Reset() {
	*x = GenerateFixturesRequest{}
	mi := &file_proto_bootstrap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFixturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFixturesRequest) ProtoMessage() {}

func (x *GenerateFixturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFixturesRequest.ProtoReflect.Descriptor instead.
func (*GenerateFixturesRequest) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateFixturesRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GenerateFixturesRequest) GetRowsJson() []byte {
	if x != nil {
		return x.RowsJson
	}
	return nil
}

func (x *GenerateFixturesRequest) GetColumnKinds() map[string]*ColumnKinds {
	if x != nil {
		return x.ColumnKinds
	}
	return nil
}

type GenerateFixturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFixturesResponse) Reset() {
	*x = GenerateFixturesResponse{}
	mi := &file_proto_bootstrap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFixturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFixturesResponse) ProtoMessage() {}

func (x *GenerateFixturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bootstrap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFixturesResponse.ProtoReflect.Descriptor instead.
func (*GenerateFixturesResponse) Descriptor() ([]byte, []int) {
	return file_proto_bootstrap_proto_rawDescGZIP(), []int{11}
}

var File_proto_bootstrap_proto protoreflect.FileDescriptor

const file_proto_bootstrap_proto_rawDesc = "" +
	"\n" +
	"\x15proto/bootstrap.proto\x12\x04gist\x1a\x12proto/common.proto\"\xad\x03\n" +
	"\x0eEndpointSchema\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"deprecated\x18\a \x01(\bR\n" +
	"deprecated\x12'\n" +
	"\x0fsecurity_scheme\x18\b \x01(\tR\x0esecurityScheme\x12#\n" +
	"\x06fields\x18\t \x03(\v2\v.gist.FieldR\x06fields\x120\n" +
	"\routput_fields\x18\n" +
	" \x03(\v2\v.gist.FieldR\foutputFields\x12\x12\n" +
	"\x04mock\x18\v \x01(\fR\x04mock\x12<\n" +
	"\x0fexpected_errors\x18\f \x03(\v2\x13.gist.ExpectedErrorR\x0eexpectedErrors\x12!\n" +
	"\fcontent_type\x18\r \x01(\tR\vcontentType\"3\n" +
	"\x10HandshakeRequest\x12\x1f\n" +
	"\vsdk_version\x18\x01 \x01(\tR\n" +
	"sdkVersion\"\x13\n" +
	"\x11HandshakeResponse\"^\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12,\n" +
	"\x06schema\x18\x02 \x01(\v2\x14.gist.EndpointSchemaR\x06schema\"\x12\n" +
	"\x10RegisterResponse\"N\n" +
	"\x19RegisterMiddlewareRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x17\n" +
	"\x15RegisterMiddlewareAck\"\x1c\n" +
	"\x1aValidateMiddlewaresRequest\"7\n" +
	"\x1bValidateMiddlewaresResponse\x12\x18\n" +
	"\amissing\x18\x01 \x03(\tR\amissing\"{\n" +
	"\vColumnKinds\x122\n" +
	"\x05kinds\x18\x01 \x03(\v2\x1c.gist.ColumnKinds.KindsEntryR\x05kinds\x1a8\n" +
	"\n" +
	"KindsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x01\n" +
	"\x17GenerateFixturesRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\trows_json\x18\x02 \x01(\fR\browsJson\x12Q\n" +
	"\fcolumn_kinds\x18\x03 \x03(\v2..gist.GenerateFixturesRequest.ColumnKindsEntryR\vcolumnKinds\x1aQ\n" +
	"\x10ColumnKindsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.gist.ColumnKindsR\x05value:\x028\x01\"\x1a\n" +
	"\x18GenerateFixturesResponse2\x8e\x03\n" +
	"\x10BootstrapService\x12<\n" +
	"\tHandshake\x12\x16.gist.HandshakeRequest\x1a\x17.gist.HandshakeResponse\x129\n" +
	"\bRegister\x12\x15.gist.RegisterRequest\x1a\x16.gist.RegisterResponse\x12R\n" +
	"\x12RegisterMiddleware\x12\x1f.gist.RegisterMiddlewareRequest\x1a\x1b.gist.RegisterMiddlewareAck\x12Z\n" +
	"\x13ValidateMiddlewares\x12 .gist.ValidateMiddlewaresRequest\x1a!.gist.ValidateMiddlewaresResponse\x12Q\n" +
	"\x10GenerateFixtures\x12\x1d.gist.GenerateFixturesRequest\x1a\x1e.gist.GenerateFixturesResponseB&Z$github.com/wieoapps/gist/proto;protob\x06proto3"

var (
	file_proto_bootstrap_proto_rawDescOnce sync.Once
	file_proto_bootstrap_proto_rawDescData []byte
)

func file_proto_bootstrap_proto_rawDescGZIP() []byte {
	file_proto_bootstrap_proto_rawDescOnce.Do(func() {
		file_proto_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bootstrap_proto_rawDesc), len(file_proto_bootstrap_proto_rawDesc)))
	})
	return file_proto_bootstrap_proto_rawDescData
}

var file_proto_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_bootstrap_proto_goTypes = []any{
	(*EndpointSchema)(nil),              // 0: gist.EndpointSchema
	(*HandshakeRequest)(nil),            // 1: gist.HandshakeRequest
	(*HandshakeResponse)(nil),           // 2: gist.HandshakeResponse
	(*RegisterRequest)(nil),             // 3: gist.RegisterRequest
	(*RegisterResponse)(nil),            // 4: gist.RegisterResponse
	(*RegisterMiddlewareRequest)(nil),   // 5: gist.RegisterMiddlewareRequest
	(*RegisterMiddlewareAck)(nil),       // 6: gist.RegisterMiddlewareAck
	(*ValidateMiddlewaresRequest)(nil),  // 7: gist.ValidateMiddlewaresRequest
	(*ValidateMiddlewaresResponse)(nil), // 8: gist.ValidateMiddlewaresResponse
	(*ColumnKinds)(nil),                 // 9: gist.ColumnKinds
	(*GenerateFixturesRequest)(nil),     // 10: gist.GenerateFixturesRequest
	(*GenerateFixturesResponse)(nil),    // 11: gist.GenerateFixturesResponse
	nil,                                 // 12: gist.ColumnKinds.KindsEntry
	nil,                                 // 13: gist.GenerateFixturesRequest.ColumnKindsEntry
	(*Field)(nil),                       // 14: gist.Field
	(*ExpectedError)(nil),               // 15: gist.ExpectedError
}
var file_proto_bootstrap_proto_depIdxs = []int32{
	14, // 0: gist.EndpointSchema.fields:type_name -> gist.Field
	14, // 1: gist.EndpointSchema.output_fields:type_name -> gist.Field
	15, // 2: gist.EndpointSchema.expected_errors:type_name -> gist.ExpectedError
	0,  // 3: gist.RegisterRequest.schema:type_name -> gist.EndpointSchema
	12, // 4: gist.ColumnKinds.kinds:type_name -> gist.ColumnKinds.KindsEntry
	13, // 5: gist.GenerateFixturesRequest.column_kinds:type_name -> gist.GenerateFixturesRequest.ColumnKindsEntry
	9,  // 6: gist.GenerateFixturesRequest.ColumnKindsEntry.value:type_name -> gist.ColumnKinds
	1,  // 7: gist.BootstrapService.Handshake:input_type -> gist.HandshakeRequest
	3,  // 8: gist.BootstrapService.Register:input_type -> gist.RegisterRequest
	5,  // 9: gist.BootstrapService.RegisterMiddleware:input_type -> gist.RegisterMiddlewareRequest
	7,  // 10: gist.BootstrapService.ValidateMiddlewares:input_type -> gist.ValidateMiddlewaresRequest
	10, // 11: gist.BootstrapService.GenerateFixtures:input_type -> gist.GenerateFixturesRequest
	2,  // 12: gist.BootstrapService.Handshake:output_type -> gist.HandshakeResponse
	4,  // 13: gist.BootstrapService.Register:output_type -> gist.RegisterResponse
	6,  // 14: gist.BootstrapService.RegisterMiddleware:output_type -> gist.RegisterMiddlewareAck
	8,  // 15: gist.BootstrapService.ValidateMiddlewares:output_type -> gist.ValidateMiddlewaresResponse
	11, // 16: gist.BootstrapService.GenerateFixtures:output_type -> gist.GenerateFixturesResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_bootstrap_proto_init() }
func file_proto_bootstrap_proto_init() {
	if File_proto_bootstrap_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bootstrap_proto_rawDesc), len(file_proto_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bootstrap_proto_goTypes,
		DependencyIndexes: file_proto_bootstrap_proto_depIdxs,
		MessageInfos:      file_proto_bootstrap_proto_msgTypes,
	}.Build()
	File_proto_bootstrap_proto = out.File
	file_proto_bootstrap_proto_goTypes = nil
	file_proto_bootstrap_proto_depIdxs = nil
}
