// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/callback.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallbackService_Invoke_FullMethodName             = "/gist.CallbackService/Invoke"
	CallbackService_InvokeMiddleware_FullMethodName   = "/gist.CallbackService/InvokeMiddleware"
	CallbackService_StartCustomService_FullMethodName = "/gist.CallbackService/StartCustomService"
	CallbackService_StopCustomService_FullMethodName  = "/gist.CallbackService/StopCustomService"
	CallbackService_Tick_FullMethodName               = "/gist.CallbackService/Tick"
	CallbackService_Deliver_FullMethodName            = "/gist.CallbackService/Deliver"
)

// CallbackServiceClient is the client API for CallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallbackServiceClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	InvokeMiddleware(ctx context.Context, in *InvokeMiddlewareRequest, opts ...grpc.CallOption) (*InvokeMiddlewareResponse, error)
	StartCustomService(ctx context.Context, in *StartCustomServiceRequest, opts ...grpc.CallOption) (*CustomServiceAck, error)
	StopCustomService(ctx context.Context, in *StopCustomServiceRequest, opts ...grpc.CallOption) (*CustomServiceAck, error)
	Tick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*TickAck, error)
	Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverAck, error)
}

type callbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallbackServiceClient(cc grpc.ClientConnInterface) CallbackServiceClient {
	return &callbackServiceClient{cc}
}

func (c *callbackServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, CallbackService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callbackServiceClient) InvokeMiddleware(ctx context.Context, in *InvokeMiddlewareRequest, opts ...grpc.CallOption) (*InvokeMiddlewareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeMiddlewareResponse)
	err := c.cc.Invoke(ctx, CallbackService_InvokeMiddleware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callbackServiceClient) StartCustomService(ctx context.Context, in *StartCustomServiceRequest, opts ...grpc.CallOption) (*CustomServiceAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomServiceAck)
	err := c.cc.Invoke(ctx, CallbackService_StartCustomService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callbackServiceClient) StopCustomService(ctx context.Context, in *StopCustomServiceRequest, opts ...grpc.CallOption) (*CustomServiceAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomServiceAck)
	err := c.cc.Invoke(ctx, CallbackService_StopCustomService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callbackServiceClient) Tick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*TickAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TickAck)
	err := c.cc.Invoke(ctx, CallbackService_Tick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callbackServiceClient) Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverAck)
	err := c.cc.Invoke(ctx, CallbackService_Deliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallbackServiceServer is the server API for CallbackService service.
// All implementations must embed UnimplementedCallbackServiceServer
// for forward compatibility.
type CallbackServiceServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	InvokeMiddleware(context.Context, *InvokeMiddlewareRequest) (*InvokeMiddlewareResponse, error)
	StartCustomService(context.Context, *StartCustomServiceRequest) (*CustomServiceAck, error)
	StopCustomService(context.Context, *StopCustomServiceRequest) (*CustomServiceAck, error)
	Tick(context.Context, *TickRequest) (*TickAck, error)
	Deliver(context.Context, *DeliverRequest) (*DeliverAck, error)
	mustEmbedUnimplementedCallbackServiceServer()
}

// UnimplementedCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallbackServiceServer struct{}

func (UnimplementedCallbackServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedCallbackServiceServer) InvokeMiddleware(context.Context, *InvokeMiddlewareRequest) (*InvokeMiddlewareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeMiddleware not implemented")
}
func (UnimplementedCallbackServiceServer) StartCustomService(context.Context, *StartCustomServiceRequest) (*CustomServiceAck, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCustomService not implemented")
}
func (UnimplementedCallbackServiceServer) StopCustomService(context.Context, *StopCustomServiceRequest) (*CustomServiceAck, error) {
	return nil, status.Error(codes.Unimplemented, "method StopCustomService not implemented")
}
func (UnimplementedCallbackServiceServer) Tick(context.Context, *TickRequest) (*TickAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Tick not implemented")
}
func (UnimplementedCallbackServiceServer) Deliver(context.Context, *DeliverRequest) (*DeliverAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedCallbackServiceServer) mustEmbedUnimplementedCallbackServiceServer() {}
func (UnimplementedCallbackServiceServer) testEmbeddedByValue()                         {}

// UnsafeCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallbackServiceServer will
// result in compilation errors.
type UnsafeCallbackServiceServer interface {
	mustEmbedUnimplementedCallbackServiceServer()
}

func RegisterCallbackServiceServer(s grpc.ServiceRegistrar, srv CallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallbackService_ServiceDesc, srv)
}

func _CallbackService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbackServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallbackService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbackServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallbackService_InvokeMiddleware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeMiddlewareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbackServiceServer).InvokeMiddleware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallbackService_InvokeMiddleware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbackServiceServer).InvokeMiddleware(ctx, req.(*InvokeMiddlewareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallbackService_StartCustomService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCustomServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbackServiceServer).StartCustomService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallbackService_StartCustomService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbackServiceServer).StartCustomService(ctx, req.(*StartCustomServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallbackService_StopCustomService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCustomServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbackServiceServer).StopCustomService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallbackService_StopCustomService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbackServiceServer).StopCustomService(ctx, req.(*StopCustomServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallbackService_Tick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbackServiceServer).Tick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallbackService_Tick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbackServiceServer).Tick(ctx, req.(*TickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallbackService_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbackServiceServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallbackService_Deliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbackServiceServer).Deliver(ctx, req.(*DeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CallbackService_ServiceDesc is the grpc.ServiceDesc for CallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gist.CallbackService",
	HandlerType: (*CallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _CallbackService_Invoke_Handler,
		},
		{
			MethodName: "InvokeMiddleware",
			Handler:    _CallbackService_InvokeMiddleware_Handler,
		},
		{
			MethodName: "StartCustomService",
			Handler:    _CallbackService_StartCustomService_Handler,
		},
		{
			MethodName: "StopCustomService",
			Handler:    _CallbackService_StopCustomService_Handler,
		},
		{
			MethodName: "Tick",
			Handler:    _CallbackService_Tick_Handler,
		},
		{
			MethodName: "Deliver",
			Handler:    _CallbackService_Deliver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/callback.proto",
}
