// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/callback.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`                                // JSON-encoded decoded input
	AuthSubject   string                 `protobuf:"bytes,3,opt,name=auth_subject,json=authSubject,proto3" json:"auth_subject,omitempty"` // validated JWT subject (UUID), empty if none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_proto_callback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *InvokeRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *InvokeRequest) GetAuthSubject() string {
	if x != nil {
		return x.AuthSubject
	}
	return ""
}

type InvokeResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Output       []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`                         // JSON-encoded output, on success
	ErrorCode    int32                  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // a status.Code value; 0 (OK) means no error
	ErrorMessage string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// error_trace_id is set only when error_message is the endpoint's
	// declared default message rather than the real error's own text
	// (see BubbleUpErrors) - the real error was logged server-side
	// (gist-sdk's Server.Logger, itself forwarded to gist-server's own
	// log via LoggingService) tagged with this exact value, so searching
	// a customer's log for it finds the real error behind a public
	// response that otherwise reveals nothing about it.
	ErrorTraceId  string `protobuf:"bytes,4,opt,name=error_trace_id,json=errorTraceId,proto3" json:"error_trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_proto_callback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *InvokeResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *InvokeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InvokeResponse) GetErrorTraceId() string {
	if x != nil {
		return x.ErrorTraceId
	}
	return ""
}

// StartCustomServiceRequest/StopCustomServiceRequest generalize the
// gist-api callback pattern to config.json's arbitrary, customer-named
// services.<kind> entries (anything besides the three built-in kinds -
// gist-api/gist-mysql/gist-fixtures). gist-server never interprets a
// custom kind's config - config_json is that entry's own JSON object,
// opaque, passed through as-is; the customer's process (which registered
// a handler for kind via gistsdk.RegisterCustomService) is the only side
// that ever understands its shape. This is gist-server's OnStart/OnStop
// lifecycle hook (plugins/config/service_registry.go's Hook) made
// cross-process: the "spawn" a custom service gets is this call, not a
// literal subprocess - the actual logic always runs in the customer's
// own process, same as every other service on this pattern.
type StartCustomServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ConfigJson    []byte                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCustomServiceRequest) Reset() {
	*x = StartCustomServiceRequest{}
	mi := &file_proto_callback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCustomServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCustomServiceRequest) ProtoMessage() {}

func (x *StartCustomServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCustomServiceRequest.ProtoReflect.Descriptor instead.
func (*StartCustomServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{2}
}

func (x *StartCustomServiceRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StartCustomServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartCustomServiceRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type StopCustomServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCustomServiceRequest) Reset() {
	*x = StopCustomServiceRequest{}
	mi := &file_proto_callback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCustomServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCustomServiceRequest) ProtoMessage() {}

func (x *StopCustomServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCustomServiceRequest.ProtoReflect.Descriptor instead.
func (*StopCustomServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{3}
}

func (x *StopCustomServiceRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StopCustomServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CustomServiceAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomServiceAck) Reset() {
	*x = CustomServiceAck{}
	mi := &file_proto_callback_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomServiceAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomServiceAck) ProtoMessage() {}

func (x *CustomServiceAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomServiceAck.ProtoReflect.Descriptor instead.
func (*CustomServiceAck) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{4}
}

func (x *CustomServiceAck) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CustomServiceAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// CallbackService is served by the customer's stub process and called
// by gist-server whenever a real (non-mocked) request needs the
// customer's own business logic run.
// TickRequest is gist-scheduler's callback - a port of
// plugins/services/gist_scheduler: gist-server owns the actual
// cron.Cron instance and does the scheduling; on every tick, it calls
// back into the customer's process (this, not a literal timer in the
// customer's own code) to run whatever RegisterScheduleFunc(id, ...)
// registered for that schedule's id.
type TickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickRequest) Reset() {
	*x = TickRequest{}
	mi := &file_proto_callback_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickRequest) ProtoMessage() {}

func (x *TickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickRequest.ProtoReflect.Descriptor instead.
func (*TickRequest) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{5}
}

func (x *TickRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TickAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickAck) Reset() {
	*x = TickAck{}
	mi := &file_proto_callback_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickAck) ProtoMessage() {}

func (x *TickAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickAck.ProtoReflect.Descriptor instead.
func (*TickAck) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{6}
}

func (x *TickAck) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TickAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// DeliverRequest is gist-rabbit-mq-client's callback, sent once per consumed
// message for a queue StartConsumingRequest activated (see
// rabbitmq.proto) - gist-server owns the actual amqp091-go Consume loop
// and calls back into the customer's process for every delivery,
// exactly as gist-scheduler's Tick does for every cron fire. delivery_tag
// is only meaningful when that StartConsumingRequest had auto_ack =
// false - it's the value to pass to RabbitMQService's own Ack/Nack.
type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeliveryTag   uint64                 `protobuf:"varint,6,opt,name=delivery_tag,json=deliveryTag,proto3" json:"delivery_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_proto_callback_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{7}
}

func (x *DeliverRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DeliverRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *DeliverRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *DeliverRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DeliverRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DeliverRequest) GetDeliveryTag() uint64 {
	if x != nil {
		return x.DeliveryTag
	}
	return 0
}

// DeliverAck reports what the customer's handler decided to do with the
// message - ack (success), or nack with requeue true/false (failure);
// meaningless when the queue was activated with auto_ack = true, since
// gist-server has already acked by the time this call is even made.
// error_code = "not_registered" means no RegisterRabbitMQConsumer call
// has reached this (service_id, queue) pair yet - the same startup race
// Tick/StartCustomService already tolerate; gist-server nacks with
// requeue = true and retries, rather than dropping the message.
type DeliverAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Ack           bool                   `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Requeue       bool                   `protobuf:"varint,4,opt,name=requeue,proto3" json:"requeue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverAck) Reset() {
	*x = DeliverAck{}
	mi := &file_proto_callback_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverAck) ProtoMessage() {}

func (x *DeliverAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverAck.ProtoReflect.Descriptor instead.
func (*DeliverAck) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{8}
}

func (x *DeliverAck) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DeliverAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeliverAck) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *DeliverAck) GetRequeue() bool {
	if x != nil {
		return x.Requeue
	}
	return false
}

// InvokeMiddlewareRequest is one named middleware's own callback,
// dispatched from publicapi.Server.serve() right after auth checks, in
// the same position plugins/services/gist_api/handler.go's own
// middleware chain (apiKey -> userAuths -> custom middlewares) ran a
// customer-registered api.CustomMiddleware - restoring the same
// capability across the process boundary the two-process split
// introduced, since an arbitrary func(http.Handler) http.Handler can no
// longer run in gist-server's own process. Deliberately narrower than
// that old, full net/http access: method/path/headers/query only, no
// request body (most real registered middlewares - custom auth, rate
// limiting, request logging - never touched it, and reading it here
// would mean marshaling a full body copy per middleware per request).
type InvokeMiddlewareRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EndpointId    string                   `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Method        string                   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueryParams   map[string]string        `protobuf:"bytes,6,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeMiddlewareRequest) Reset() {
	*x = InvokeMiddlewareRequest{}
	mi := &file_proto_callback_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeMiddlewareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeMiddlewareRequest) ProtoMessage() {}

func (x *InvokeMiddlewareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeMiddlewareRequest.ProtoReflect.Descriptor instead.
func (*InvokeMiddlewareRequest) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeMiddlewareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InvokeMiddlewareRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *InvokeMiddlewareRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeMiddlewareRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InvokeMiddlewareRequest) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeMiddlewareRequest) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

// InvokeMiddlewareResponse: blocked = true means the middleware decided
// the request should go no further - status_code/headers/body are what
// publicapi.Server.serve() writes back verbatim instead of continuing
// to the endpoint's own handler. blocked = false (headers/body/
// status_code unused) means proceed normally. error_code/error_message/
// error_trace_id mirror InvokeResponse's own triple, for when the
// middleware func itself errors - a distinct outcome from a deliberate
// block.
type InvokeMiddlewareResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Blocked       bool                     `protobuf:"varint,1,opt,name=blocked,proto3" json:"blocked,omitempty"`
	StatusCode    int32                    `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ErrorCode     int32                    `protobuf:"varint,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                   `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorTraceId  string                   `protobuf:"bytes,7,opt,name=error_trace_id,json=errorTraceId,proto3" json:"error_trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeMiddlewareResponse) Reset() {
	*x = InvokeMiddlewareResponse{}
	mi := &file_proto_callback_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeMiddlewareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeMiddlewareResponse) ProtoMessage() {}

func (x *InvokeMiddlewareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callback_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeMiddlewareResponse.ProtoReflect.Descriptor instead.
func (*InvokeMiddlewareResponse) Descriptor() ([]byte, []int) {
	return file_proto_callback_proto_rawDescGZIP(), []int{10}
}

func (x *InvokeMiddlewareResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *InvokeMiddlewareResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *InvokeMiddlewareResponse) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeMiddlewareResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InvokeMiddlewareResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *InvokeMiddlewareResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InvokeMiddlewareResponse) GetErrorTraceId() string {
	if x != nil {
		return x.ErrorTraceId
	}
	return ""
}

var File_proto_callback_proto protoreflect.FileDescriptor

const file_proto_callback_proto_rawDesc = "" +
	"\n" +
	"\x14proto/callback.proto\x12\x04gist\x1a\x16proto/httpclient.proto\"i\n" +
	"\rInvokeRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12!\n" +
	"\fauth_subject\x18\x03 \x01(\tR\vauthSubject\"\x92\x01\n" +
	"\x0eInvokeResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12$\n" +
	"\x0eerror_trace_id\x18\x04 \x01(\tR\ferrorTraceId\"`\n" +
	"\x19StartCustomServiceRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\">\n" +
	"\x18StopCustomServiceRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"V\n" +
	"\x10CustomServiceAck\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x1d\n" +
	"\vTickRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\aTickAck\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x98\x02\n" +
	"\x0eDeliverRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12;\n" +
	"\aheaders\x18\x05 \x03(\v2!.gist.DeliverRequest.HeadersEntryR\aheaders\x12!\n" +
	"\fdelivery_tag\x18\x06 \x01(\x04R\vdeliveryTag\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\n" +
	"DeliverAck\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x10\n" +
	"\x03ack\x18\x03 \x01(\bR\x03ack\x12\x18\n" +
	"\arequeue\x18\x04 \x01(\bR\arequeue\"\xa3\x03\n" +
	"\x17InvokeMiddlewareRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12D\n" +
	"\aheaders\x18\x05 \x03(\v2*.gist.InvokeMiddlewareRequest.HeadersEntryR\aheaders\x12Q\n" +
	"\fquery_params\x18\x06 \x03(\v2..gist.InvokeMiddlewareRequest.QueryParamsEntryR\vqueryParams\x1aN\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.gist.HeaderValuesR\x05value:\x028\x01\x1a>\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xea\x02\n" +
	"\x18InvokeMiddlewareResponse\x12\x18\n" +
	"\ablocked\x18\x01 \x01(\bR\ablocked\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12E\n" +
	"\aheaders\x18\x03 \x03(\v2+.gist.InvokeMiddlewareResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12$\n" +
	"\x0eerror_trace_id\x18\a \x01(\tR\ferrorTraceId\x1aN\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.gist.HeaderValuesR\x05value:\x028\x012\x92\x03\n" +
	"\x0fCallbackService\x123\n" +
	"\x06Invoke\x12\x13.gist.InvokeRequest\x1a\x14.gist.InvokeResponse\x12Q\n" +
	"\x10InvokeMiddleware\x12\x1d.gist.InvokeMiddlewareRequest\x1a\x1e.gist.InvokeMiddlewareResponse\x12M\n" +
	"\x12StartCustomService\x12\x1f.gist.StartCustomServiceRequest\x1a\x16.gist.CustomServiceAck\x12K\n" +
	"\x11StopCustomService\x12\x1e.gist.StopCustomServiceRequest\x1a\x16.gist.CustomServiceAck\x12(\n" +
	"\x04Tick\x12\x11.gist.TickRequest\x1a\r.gist.TickAck\x121\n" +
	"\aDeliver\x12\x14.gist.DeliverRequest\x1a\x10.gist.DeliverAckB&Z$github.com/wieoapps/gist/proto;protob\x06proto3"

var (
	file_proto_callback_proto_rawDescOnce sync.Once
	file_proto_callback_proto_rawDescData []byte
)

func file_proto_callback_proto_rawDescGZIP() []byte {
	file_proto_callback_proto_rawDescOnce.Do(func() {
		file_proto_callback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_callback_proto_rawDesc), len(file_proto_callback_proto_rawDesc)))
	})
	return file_proto_callback_proto_rawDescData
}

var file_proto_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_callback_proto_goTypes = []any{
	(*InvokeRequest)(nil),             // 0: gist.InvokeRequest
	(*InvokeResponse)(nil),            // 1: gist.InvokeResponse
	(*StartCustomServiceRequest)(nil), // 2: gist.StartCustomServiceRequest
	(*StopCustomServiceRequest)(nil),  // 3: gist.StopCustomServiceRequest
	(*CustomServiceAck)(nil),          // 4: gist.CustomServiceAck
	(*TickRequest)(nil),               // 5: gist.TickRequest
	(*TickAck)(nil),                   // 6: gist.TickAck
	(*DeliverRequest)(nil),            // 7: gist.DeliverRequest
	(*DeliverAck)(nil),                // 8: gist.DeliverAck
	(*InvokeMiddlewareRequest)(nil),   // 9: gist.InvokeMiddlewareRequest
	(*InvokeMiddlewareResponse)(nil),  // 10: gist.InvokeMiddlewareResponse
	nil,                               // 11: gist.DeliverRequest.HeadersEntry
	nil,                               // 12: gist.InvokeMiddlewareRequest.HeadersEntry
	nil,                               // 13: gist.InvokeMiddlewareRequest.QueryParamsEntry
	nil,                               // 14: gist.InvokeMiddlewareResponse.HeadersEntry
	(*HeaderValues)(nil),              // 15: gist.HeaderValues
}
var file_proto_callback_proto_depIdxs = []int32{
	11, // 0: gist.DeliverRequest.headers:type_name -> gist.DeliverRequest.HeadersEntry
	12, // 1: gist.InvokeMiddlewareRequest.headers:type_name -> gist.InvokeMiddlewareRequest.HeadersEntry
	13, // 2: gist.InvokeMiddlewareRequest.query_params:type_name -> gist.InvokeMiddlewareRequest.QueryParamsEntry
	14, // 3: gist.InvokeMiddlewareResponse.headers:type_name -> gist.InvokeMiddlewareResponse.HeadersEntry
	15, // 4: gist.InvokeMiddlewareRequest.HeadersEntry.value:type_name -> gist.HeaderValues
	15, // 5: gist.InvokeMiddlewareResponse.HeadersEntry.value:type_name -> gist.HeaderValues
	0,  // 6: gist.CallbackService.Invoke:input_type -> gist.InvokeRequest
	9,  // 7: gist.CallbackService.InvokeMiddleware:input_type -> gist.InvokeMiddlewareRequest
	2,  // 8: gist.CallbackService.StartCustomService:input_type -> gist.StartCustomServiceRequest
	3,  // 9: gist.CallbackService.StopCustomService:input_type -> gist.StopCustomServiceRequest
	5,  // 10: gist.CallbackService.Tick:input_type -> gist.TickRequest
	7,  // 11: gist.CallbackService.Deliver:input_type -> gist.DeliverRequest
	1,  // 12: gist.CallbackService.Invoke:output_type -> gist.InvokeResponse
	10, // 13: gist.CallbackService.InvokeMiddleware:output_type -> gist.InvokeMiddlewareResponse
	4,  // 14: gist.CallbackService.StartCustomService:output_type -> gist.CustomServiceAck
	4,  // 15: gist.CallbackService.StopCustomService:output_type -> gist.CustomServiceAck
	6,  // 16: gist.CallbackService.Tick:output_type -> gist.TickAck
	8,  // 17: gist.CallbackService.Deliver:output_type -> gist.DeliverAck
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_callback_proto_init() }
func file_proto_callback_proto_init() {
	if File_proto_callback_proto != nil {
		return
	}
	file_proto_httpclient_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_callback_proto_rawDesc), len(file_proto_callback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_callback_proto_goTypes,
		DependencyIndexes: file_proto_callback_proto_depIdxs,
		MessageInfos:      file_proto_callback_proto_msgTypes,
	}.Build()
	File_proto_callback_proto = out.File
	file_proto_callback_proto_goTypes = nil
	file_proto_callback_proto_depIdxs = nil
}
