// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Field describes one input/output field of an endpoint - the wire
// counterpart of a single Go struct field read via reflection on the
// customer's side (path/query/json tags, validation constraints).
type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	In            string                 `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`     // "path" | "query" | "json"
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // "string" | "bool" | "int" | "uint" | "float" | "any"
	Slice         bool                   `protobuf:"varint,4,opt,name=slice,proto3" json:"slice,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	MinLength     *int32                 `protobuf:"varint,6,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	MaxLength     *int32                 `protobuf:"varint,7,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	Minimum       *float64               `protobuf:"fixed64,8,opt,name=minimum,proto3,oneof" json:"minimum,omitempty"`
	Maximum       *float64               `protobuf:"fixed64,9,opt,name=maximum,proto3,oneof" json:"maximum,omitempty"`
	Pattern       string                 `protobuf:"bytes,10,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Example       string                 `protobuf:"bytes,11,opt,name=example,proto3" json:"example,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *Field) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Field) GetSlice() bool {
	if x != nil {
		return x.Slice
	}
	return false
}

func (x *Field) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Field) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *Field) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *Field) GetMinimum() float64 {
	if x != nil && x.Minimum != nil {
		return *x.Minimum
	}
	return 0
}

func (x *Field) GetMaximum() float64 {
	if x != nil && x.Maximum != nil {
		return *x.Maximum
	}
	return 0
}

func (x *Field) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Field) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

// ExpectedError declares one error code+description a handler may
// return - the wire counterpart of a plugins/services/gist_api
// errors.ExpectedError entry in an EndpointHandler call's expectedErrors
// list. gist-server uses these to document response codes and to reject
// (log-and-panic style, at the gist-sdk layer) an error code the handler
// never declared.
type ExpectedError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpectedError) Reset() {
	*x = ExpectedError{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpectedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpectedError) ProtoMessage() {}

func (x *ExpectedError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpectedError.ProtoReflect.Descriptor instead.
func (*ExpectedError) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *ExpectedError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExpectedError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\x04gist\"\xe1\x02\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02in\x18\x02 \x01(\tR\x02in\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05slice\x18\x04 \x01(\bR\x05slice\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\"\n" +
	"\n" +
	"min_length\x18\x06 \x01(\x05H\x00R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\a \x01(\x05H\x01R\tmaxLength\x88\x01\x01\x12\x1d\n" +
	"\aminimum\x18\b \x01(\x01H\x02R\aminimum\x88\x01\x01\x12\x1d\n" +
	"\amaximum\x18\t \x01(\x01H\x03R\amaximum\x88\x01\x01\x12\x18\n" +
	"\apattern\x18\n" +
	" \x01(\tR\apattern\x12\x18\n" +
	"\aexample\x18\v \x01(\tR\aexampleB\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_lengthB\n" +
	"\n" +
	"\b_minimumB\n" +
	"\n" +
	"\b_maximum\"E\n" +
	"\rExpectedError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescriptionB&Z$github.com/wieoapps/gist/proto;protob\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_common_proto_goTypes = []any{
	(*Field)(nil),         // 0: gist.Field
	(*ExpectedError)(nil), // 1: gist.ExpectedError
}
var file_proto_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	file_proto_common_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
