// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/gcs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GoogleCloudStorageService is a port of plugins/services/gist_googlecloudstorage's two
// real exported methods (Exists/Store), extended with full CRUD for
// both buckets and objects. File/object bytes cross the wire as a plain
// field - fine for the sizes this is meant for (the original itself
// takes a single *multipart.FileHeader per call, not a streaming
// upload). Every *_id/bucket_id below is the customer's own
// config.json-defined bucket id (see gist-google-cloud-storage-client's Config.Buckets), not a
// raw GoogleCloudStorage bucket name - resolved server-side the same way Exists/Store
// already do.
type GoogleCloudStorageExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageExistsRequest) Reset() {
	*x = GoogleCloudStorageExistsRequest{}
	mi := &file_proto_gcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageExistsRequest) ProtoMessage() {}

func (x *GoogleCloudStorageExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageExistsRequest.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{0}
}

func (x *GoogleCloudStorageExistsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GoogleCloudStorageExistsRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *GoogleCloudStorageExistsRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GoogleCloudStorageExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageExistsResponse) Reset() {
	*x = GoogleCloudStorageExistsResponse{}
	mi := &file_proto_gcs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageExistsResponse) ProtoMessage() {}

func (x *GoogleCloudStorageExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageExistsResponse.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{1}
}

func (x *GoogleCloudStorageExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GoogleCloudStorageExistsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GoogleCloudStorageExistsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GoogleCloudStorageStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileBytes     []byte                 `protobuf:"bytes,5,opt,name=file_bytes,json=fileBytes,proto3" json:"file_bytes,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // optional - defaults to application/octet-stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageStoreRequest) Reset() {
	*x = GoogleCloudStorageStoreRequest{}
	mi := &file_proto_gcs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageStoreRequest) ProtoMessage() {}

func (x *GoogleCloudStorageStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageStoreRequest.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageStoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{2}
}

func (x *GoogleCloudStorageStoreRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GoogleCloudStorageStoreRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *GoogleCloudStorageStoreRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GoogleCloudStorageStoreRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GoogleCloudStorageStoreRequest) GetFileBytes() []byte {
	if x != nil {
		return x.FileBytes
	}
	return nil
}

func (x *GoogleCloudStorageStoreRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type GoogleCloudStorageStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageStoreResponse) Reset() {
	*x = GoogleCloudStorageStoreResponse{}
	mi := &file_proto_gcs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageStoreResponse) ProtoMessage() {}

func (x *GoogleCloudStorageStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageStoreResponse.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageStoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{3}
}

func (x *GoogleCloudStorageStoreResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GoogleCloudStorageStoreResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GoogleCloudStorageStoreResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GoogleCloudStorageStoreResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GoogleCloudStorageCreateBucketRequest/Response creates a new bucket - a 409 (bucket
// name already taken, by this project or another) reports created=false
// rather than an error, the same "conflict isn't necessarily a failure"
// convention ElasticsearchService's CreateItem uses.
type GoogleCloudStorageCreateBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"` // e.g. "US" - see https://cloud.google.com/storage/docs/locations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageCreateBucketRequest) Reset() {
	*x = GoogleCloudStorageCreateBucketRequest{}
	mi := &file_proto_gcs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageCreateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageCreateBucketRequest) ProtoMessage() {}

func (x *GoogleCloudStorageCreateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageCreateBucketRequest.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageCreateBucketRequest) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{4}
}

func (x *GoogleCloudStorageCreateBucketRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GoogleCloudStorageCreateBucketRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *GoogleCloudStorageCreateBucketRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type GoogleCloudStorageCreateBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageCreateBucketResponse) Reset() {
	*x = GoogleCloudStorageCreateBucketResponse{}
	mi := &file_proto_gcs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageCreateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageCreateBucketResponse) ProtoMessage() {}

func (x *GoogleCloudStorageCreateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageCreateBucketResponse.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageCreateBucketResponse) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{5}
}

func (x *GoogleCloudStorageCreateBucketResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GoogleCloudStorageCreateBucketResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GoogleCloudStorageCreateBucketResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GoogleCloudStorageGetBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageGetBucketRequest) Reset() {
	*x = GoogleCloudStorageGetBucketRequest{}
	mi := &file_proto_gcs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageGetBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageGetBucketRequest) ProtoMessage() {}

func (x *GoogleCloudStorageGetBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageGetBucketRequest.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageGetBucketRequest) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{6}
}

func (x *GoogleCloudStorageGetBucketRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GoogleCloudStorageGetBucketRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

type GoogleCloudStorageGetBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	AttrsJson     []byte                 `protobuf:"bytes,4,opt,name=attrs_json,json=attrsJson,proto3" json:"attrs_json,omitempty"` // the bucket's metadata resource, present only if found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageGetBucketResponse) Reset() {
	*x = GoogleCloudStorageGetBucketResponse{}
	mi := &file_proto_gcs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageGetBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageGetBucketResponse) ProtoMessage() {}

func (x *GoogleCloudStorageGetBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageGetBucketResponse.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageGetBucketResponse) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{7}
}

func (x *GoogleCloudStorageGetBucketResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GoogleCloudStorageGetBucketResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GoogleCloudStorageGetBucketResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GoogleCloudStorageGetBucketResponse) GetAttrsJson() []byte {
	if x != nil {
		return x.AttrsJson
	}
	return nil
}

type GoogleCloudStorageUpdateBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	AttrsJson     []byte                 `protobuf:"bytes,3,opt,name=attrs_json,json=attrsJson,proto3" json:"attrs_json,omitempty"` // partial bucket metadata to merge, e.g. {"labels":{...}}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageUpdateBucketRequest) Reset() {
	*x = GoogleCloudStorageUpdateBucketRequest{}
	mi := &file_proto_gcs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageUpdateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageUpdateBucketRequest) ProtoMessage() {}

func (x *GoogleCloudStorageUpdateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageUpdateBucketRequest.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageUpdateBucketRequest) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{8}
}

func (x *GoogleCloudStorageUpdateBucketRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GoogleCloudStorageUpdateBucketRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *GoogleCloudStorageUpdateBucketRequest) GetAttrsJson() []byte {
	if x != nil {
		return x.AttrsJson
	}
	return nil
}

type GoogleCloudStorageUpdateBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageUpdateBucketResponse) Reset() {
	*x = GoogleCloudStorageUpdateBucketResponse{}
	mi := &file_proto_gcs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageUpdateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageUpdateBucketResponse) ProtoMessage() {}

func (x *GoogleCloudStorageUpdateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageUpdateBucketResponse.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageUpdateBucketResponse) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{9}
}

func (x *GoogleCloudStorageUpdateBucketResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GoogleCloudStorageUpdateBucketResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GoogleCloudStorageUpdateBucketResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GoogleCloudStorageDeleteBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageDeleteBucketRequest) Reset() {
	*x = GoogleCloudStorageDeleteBucketRequest{}
	mi := &file_proto_gcs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageDeleteBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageDeleteBucketRequest) ProtoMessage() {}

func (x *GoogleCloudStorageDeleteBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageDeleteBucketRequest.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageDeleteBucketRequest) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{10}
}

func (x *GoogleCloudStorageDeleteBucketRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GoogleCloudStorageDeleteBucketRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

type GoogleCloudStorageDeleteBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageDeleteBucketResponse) Reset() {
	*x = GoogleCloudStorageDeleteBucketResponse{}
	mi := &file_proto_gcs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageDeleteBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageDeleteBucketResponse) ProtoMessage() {}

func (x *GoogleCloudStorageDeleteBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageDeleteBucketResponse.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageDeleteBucketResponse) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{11}
}

func (x *GoogleCloudStorageDeleteBucketResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GoogleCloudStorageDeleteBucketResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GoogleCloudStorageDeleteBucketResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GoogleCloudStorageGetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageGetObjectRequest) Reset() {
	*x = GoogleCloudStorageGetObjectRequest{}
	mi := &file_proto_gcs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageGetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageGetObjectRequest) ProtoMessage() {}

func (x *GoogleCloudStorageGetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageGetObjectRequest.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageGetObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{12}
}

func (x *GoogleCloudStorageGetObjectRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GoogleCloudStorageGetObjectRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *GoogleCloudStorageGetObjectRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GoogleCloudStorageGetObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // the object's raw bytes, present only if found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageGetObjectResponse) Reset() {
	*x = GoogleCloudStorageGetObjectResponse{}
	mi := &file_proto_gcs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageGetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageGetObjectResponse) ProtoMessage() {}

func (x *GoogleCloudStorageGetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageGetObjectResponse.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageGetObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{13}
}

func (x *GoogleCloudStorageGetObjectResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GoogleCloudStorageGetObjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GoogleCloudStorageGetObjectResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GoogleCloudStorageGetObjectResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GoogleCloudStorageUpdateObjectMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageUpdateObjectMetadataRequest) Reset() {
	*x = GoogleCloudStorageUpdateObjectMetadataRequest{}
	mi := &file_proto_gcs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageUpdateObjectMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageUpdateObjectMetadataRequest) ProtoMessage() {}

func (x *GoogleCloudStorageUpdateObjectMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageUpdateObjectMetadataRequest.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageUpdateObjectMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{14}
}

func (x *GoogleCloudStorageUpdateObjectMetadataRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GoogleCloudStorageUpdateObjectMetadataRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *GoogleCloudStorageUpdateObjectMetadataRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GoogleCloudStorageUpdateObjectMetadataRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GoogleCloudStorageUpdateObjectMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // the object's full custom metadata after the update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageUpdateObjectMetadataResponse) Reset() {
	*x = GoogleCloudStorageUpdateObjectMetadataResponse{}
	mi := &file_proto_gcs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageUpdateObjectMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageUpdateObjectMetadataResponse) ProtoMessage() {}

func (x *GoogleCloudStorageUpdateObjectMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageUpdateObjectMetadataResponse.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageUpdateObjectMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{15}
}

func (x *GoogleCloudStorageUpdateObjectMetadataResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GoogleCloudStorageUpdateObjectMetadataResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GoogleCloudStorageUpdateObjectMetadataResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GoogleCloudStorageUpdateObjectMetadataResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GoogleCloudStorageDeleteObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageDeleteObjectRequest) Reset() {
	*x = GoogleCloudStorageDeleteObjectRequest{}
	mi := &file_proto_gcs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageDeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageDeleteObjectRequest) ProtoMessage() {}

func (x *GoogleCloudStorageDeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageDeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageDeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{16}
}

func (x *GoogleCloudStorageDeleteObjectRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GoogleCloudStorageDeleteObjectRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *GoogleCloudStorageDeleteObjectRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GoogleCloudStorageDeleteObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCloudStorageDeleteObjectResponse) Reset() {
	*x = GoogleCloudStorageDeleteObjectResponse{}
	mi := &file_proto_gcs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorageDeleteObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorageDeleteObjectResponse) ProtoMessage() {}

func (x *GoogleCloudStorageDeleteObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorageDeleteObjectResponse.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorageDeleteObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_gcs_proto_rawDescGZIP(), []int{17}
}

func (x *GoogleCloudStorageDeleteObjectResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GoogleCloudStorageDeleteObjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GoogleCloudStorageDeleteObjectResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_proto_gcs_proto protoreflect.FileDescriptor

const file_proto_gcs_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/gcs.proto\x12\x04gist\"z\n" +
	"\x1fGoogleCloudStorageExistsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"~\n" +
	" GoogleCloudStorageExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xcf\x01\n" +
	"\x1eGoogleCloudStorageStoreRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"file_bytes\x18\x05 \x01(\fR\tfileBytes\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\"\x96\x01\n" +
	"\x1fGoogleCloudStorageStoreResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x7f\n" +
	"%GoogleCloudStorageCreateBucketRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"\x86\x01\n" +
	"&GoogleCloudStorageCreateBucketResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\"`\n" +
	"\"GoogleCloudStorageGetBucketRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\"\x9e\x01\n" +
	"#GoogleCloudStorageGetBucketResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x1d\n" +
	"\n" +
	"attrs_json\x18\x04 \x01(\fR\tattrsJson\"\x82\x01\n" +
	"%GoogleCloudStorageUpdateBucketRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12\x1d\n" +
	"\n" +
	"attrs_json\x18\x03 \x01(\fR\tattrsJson\"\x82\x01\n" +
	"&GoogleCloudStorageUpdateBucketResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"c\n" +
	"%GoogleCloudStorageDeleteBucketRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\"\x82\x01\n" +
	"&GoogleCloudStorageDeleteBucketResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"}\n" +
	"\"GoogleCloudStorageGetObjectRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"\x99\x01\n" +
	"#GoogleCloudStorageGetObjectResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"\xa4\x02\n" +
	"-GoogleCloudStorageUpdateObjectMetadataRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12]\n" +
	"\bmetadata\x18\x04 \x03(\v2A.gist.GoogleCloudStorageUpdateObjectMetadataRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x02\n" +
	".GoogleCloudStorageUpdateObjectMetadataResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12^\n" +
	"\bmetadata\x18\x04 \x03(\v2B.gist.GoogleCloudStorageUpdateObjectMetadataResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"%GoogleCloudStorageDeleteObjectRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"\x82\x01\n" +
	"&GoogleCloudStorageDeleteObjectResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found2\xbe\a\n" +
	"\x19GoogleCloudStorageService\x12W\n" +
	"\x06Exists\x12%.gist.GoogleCloudStorageExistsRequest\x1a&.gist.GoogleCloudStorageExistsResponse\x12T\n" +
	"\x05Store\x12$.gist.GoogleCloudStorageStoreRequest\x1a%.gist.GoogleCloudStorageStoreResponse\x12i\n" +
	"\fCreateBucket\x12+.gist.GoogleCloudStorageCreateBucketRequest\x1a,.gist.GoogleCloudStorageCreateBucketResponse\x12`\n" +
	"\tGetBucket\x12(.gist.GoogleCloudStorageGetBucketRequest\x1a).gist.GoogleCloudStorageGetBucketResponse\x12i\n" +
	"\fUpdateBucket\x12+.gist.GoogleCloudStorageUpdateBucketRequest\x1a,.gist.GoogleCloudStorageUpdateBucketResponse\x12i\n" +
	"\fDeleteBucket\x12+.gist.GoogleCloudStorageDeleteBucketRequest\x1a,.gist.GoogleCloudStorageDeleteBucketResponse\x12`\n" +
	"\tGetObject\x12(.gist.GoogleCloudStorageGetObjectRequest\x1a).gist.GoogleCloudStorageGetObjectResponse\x12\x81\x01\n" +
	"\x14UpdateObjectMetadata\x123.gist.GoogleCloudStorageUpdateObjectMetadataRequest\x1a4.gist.GoogleCloudStorageUpdateObjectMetadataResponse\x12i\n" +
	"\fDeleteObject\x12+.gist.GoogleCloudStorageDeleteObjectRequest\x1a,.gist.GoogleCloudStorageDeleteObjectResponseB&Z$github.com/wieoapps/gist/proto;protob\x06proto3"

var (
	file_proto_gcs_proto_rawDescOnce sync.Once
	file_proto_gcs_proto_rawDescData []byte
)

func file_proto_gcs_proto_rawDescGZIP() []byte {
	file_proto_gcs_proto_rawDescOnce.Do(func() {
		file_proto_gcs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gcs_proto_rawDesc), len(file_proto_gcs_proto_rawDesc)))
	})
	return file_proto_gcs_proto_rawDescData
}

var file_proto_gcs_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_gcs_proto_goTypes = []any{
	(*GoogleCloudStorageExistsRequest)(nil),                // 0: gist.GoogleCloudStorageExistsRequest
	(*GoogleCloudStorageExistsResponse)(nil),               // 1: gist.GoogleCloudStorageExistsResponse
	(*GoogleCloudStorageStoreRequest)(nil),                 // 2: gist.GoogleCloudStorageStoreRequest
	(*GoogleCloudStorageStoreResponse)(nil),                // 3: gist.GoogleCloudStorageStoreResponse
	(*GoogleCloudStorageCreateBucketRequest)(nil),          // 4: gist.GoogleCloudStorageCreateBucketRequest
	(*GoogleCloudStorageCreateBucketResponse)(nil),         // 5: gist.GoogleCloudStorageCreateBucketResponse
	(*GoogleCloudStorageGetBucketRequest)(nil),             // 6: gist.GoogleCloudStorageGetBucketRequest
	(*GoogleCloudStorageGetBucketResponse)(nil),            // 7: gist.GoogleCloudStorageGetBucketResponse
	(*GoogleCloudStorageUpdateBucketRequest)(nil),          // 8: gist.GoogleCloudStorageUpdateBucketRequest
	(*GoogleCloudStorageUpdateBucketResponse)(nil),         // 9: gist.GoogleCloudStorageUpdateBucketResponse
	(*GoogleCloudStorageDeleteBucketRequest)(nil),          // 10: gist.GoogleCloudStorageDeleteBucketRequest
	(*GoogleCloudStorageDeleteBucketResponse)(nil),         // 11: gist.GoogleCloudStorageDeleteBucketResponse
	(*GoogleCloudStorageGetObjectRequest)(nil),             // 12: gist.GoogleCloudStorageGetObjectRequest
	(*GoogleCloudStorageGetObjectResponse)(nil),            // 13: gist.GoogleCloudStorageGetObjectResponse
	(*GoogleCloudStorageUpdateObjectMetadataRequest)(nil),  // 14: gist.GoogleCloudStorageUpdateObjectMetadataRequest
	(*GoogleCloudStorageUpdateObjectMetadataResponse)(nil), // 15: gist.GoogleCloudStorageUpdateObjectMetadataResponse
	(*GoogleCloudStorageDeleteObjectRequest)(nil),          // 16: gist.GoogleCloudStorageDeleteObjectRequest
	(*GoogleCloudStorageDeleteObjectResponse)(nil),         // 17: gist.GoogleCloudStorageDeleteObjectResponse
	nil, // 18: gist.GoogleCloudStorageUpdateObjectMetadataRequest.MetadataEntry
	nil, // 19: gist.GoogleCloudStorageUpdateObjectMetadataResponse.MetadataEntry
}
var file_proto_gcs_proto_depIdxs = []int32{
	18, // 0: gist.GoogleCloudStorageUpdateObjectMetadataRequest.metadata:type_name -> gist.GoogleCloudStorageUpdateObjectMetadataRequest.MetadataEntry
	19, // 1: gist.GoogleCloudStorageUpdateObjectMetadataResponse.metadata:type_name -> gist.GoogleCloudStorageUpdateObjectMetadataResponse.MetadataEntry
	0,  // 2: gist.GoogleCloudStorageService.Exists:input_type -> gist.GoogleCloudStorageExistsRequest
	2,  // 3: gist.GoogleCloudStorageService.Store:input_type -> gist.GoogleCloudStorageStoreRequest
	4,  // 4: gist.GoogleCloudStorageService.CreateBucket:input_type -> gist.GoogleCloudStorageCreateBucketRequest
	6,  // 5: gist.GoogleCloudStorageService.GetBucket:input_type -> gist.GoogleCloudStorageGetBucketRequest
	8,  // 6: gist.GoogleCloudStorageService.UpdateBucket:input_type -> gist.GoogleCloudStorageUpdateBucketRequest
	10, // 7: gist.GoogleCloudStorageService.DeleteBucket:input_type -> gist.GoogleCloudStorageDeleteBucketRequest
	12, // 8: gist.GoogleCloudStorageService.GetObject:input_type -> gist.GoogleCloudStorageGetObjectRequest
	14, // 9: gist.GoogleCloudStorageService.UpdateObjectMetadata:input_type -> gist.GoogleCloudStorageUpdateObjectMetadataRequest
	16, // 10: gist.GoogleCloudStorageService.DeleteObject:input_type -> gist.GoogleCloudStorageDeleteObjectRequest
	1,  // 11: gist.GoogleCloudStorageService.Exists:output_type -> gist.GoogleCloudStorageExistsResponse
	3,  // 12: gist.GoogleCloudStorageService.Store:output_type -> gist.GoogleCloudStorageStoreResponse
	5,  // 13: gist.GoogleCloudStorageService.CreateBucket:output_type -> gist.GoogleCloudStorageCreateBucketResponse
	7,  // 14: gist.GoogleCloudStorageService.GetBucket:output_type -> gist.GoogleCloudStorageGetBucketResponse
	9,  // 15: gist.GoogleCloudStorageService.UpdateBucket:output_type -> gist.GoogleCloudStorageUpdateBucketResponse
	11, // 16: gist.GoogleCloudStorageService.DeleteBucket:output_type -> gist.GoogleCloudStorageDeleteBucketResponse
	13, // 17: gist.GoogleCloudStorageService.GetObject:output_type -> gist.GoogleCloudStorageGetObjectResponse
	15, // 18: gist.GoogleCloudStorageService.UpdateObjectMetadata:output_type -> gist.GoogleCloudStorageUpdateObjectMetadataResponse
	17, // 19: gist.GoogleCloudStorageService.DeleteObject:output_type -> gist.GoogleCloudStorageDeleteObjectResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_gcs_proto_init() }
func file_proto_gcs_proto_init() {
	if File_proto_gcs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gcs_proto_rawDesc), len(file_proto_gcs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gcs_proto_goTypes,
		DependencyIndexes: file_proto_gcs_proto_depIdxs,
		MessageInfos:      file_proto_gcs_proto_msgTypes,
	}.Build()
	File_proto_gcs_proto = out.File
	file_proto_gcs_proto_goTypes = nil
	file_proto_gcs_proto_depIdxs = nil
}
