// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/gcs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoogleCloudStorageService_Exists_FullMethodName               = "/gist.GoogleCloudStorageService/Exists"
	GoogleCloudStorageService_Store_FullMethodName                = "/gist.GoogleCloudStorageService/Store"
	GoogleCloudStorageService_CreateBucket_FullMethodName         = "/gist.GoogleCloudStorageService/CreateBucket"
	GoogleCloudStorageService_GetBucket_FullMethodName            = "/gist.GoogleCloudStorageService/GetBucket"
	GoogleCloudStorageService_UpdateBucket_FullMethodName         = "/gist.GoogleCloudStorageService/UpdateBucket"
	GoogleCloudStorageService_DeleteBucket_FullMethodName         = "/gist.GoogleCloudStorageService/DeleteBucket"
	GoogleCloudStorageService_GetObject_FullMethodName            = "/gist.GoogleCloudStorageService/GetObject"
	GoogleCloudStorageService_UpdateObjectMetadata_FullMethodName = "/gist.GoogleCloudStorageService/UpdateObjectMetadata"
	GoogleCloudStorageService_DeleteObject_FullMethodName         = "/gist.GoogleCloudStorageService/DeleteObject"
)

// GoogleCloudStorageServiceClient is the client API for GoogleCloudStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoogleCloudStorageServiceClient interface {
	Exists(ctx context.Context, in *GoogleCloudStorageExistsRequest, opts ...grpc.CallOption) (*GoogleCloudStorageExistsResponse, error)
	Store(ctx context.Context, in *GoogleCloudStorageStoreRequest, opts ...grpc.CallOption) (*GoogleCloudStorageStoreResponse, error)
	CreateBucket(ctx context.Context, in *GoogleCloudStorageCreateBucketRequest, opts ...grpc.CallOption) (*GoogleCloudStorageCreateBucketResponse, error)
	GetBucket(ctx context.Context, in *GoogleCloudStorageGetBucketRequest, opts ...grpc.CallOption) (*GoogleCloudStorageGetBucketResponse, error)
	UpdateBucket(ctx context.Context, in *GoogleCloudStorageUpdateBucketRequest, opts ...grpc.CallOption) (*GoogleCloudStorageUpdateBucketResponse, error)
	DeleteBucket(ctx context.Context, in *GoogleCloudStorageDeleteBucketRequest, opts ...grpc.CallOption) (*GoogleCloudStorageDeleteBucketResponse, error)
	GetObject(ctx context.Context, in *GoogleCloudStorageGetObjectRequest, opts ...grpc.CallOption) (*GoogleCloudStorageGetObjectResponse, error)
	UpdateObjectMetadata(ctx context.Context, in *GoogleCloudStorageUpdateObjectMetadataRequest, opts ...grpc.CallOption) (*GoogleCloudStorageUpdateObjectMetadataResponse, error)
	DeleteObject(ctx context.Context, in *GoogleCloudStorageDeleteObjectRequest, opts ...grpc.CallOption) (*GoogleCloudStorageDeleteObjectResponse, error)
}

type googleCloudStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoogleCloudStorageServiceClient(cc grpc.ClientConnInterface) GoogleCloudStorageServiceClient {
	return &googleCloudStorageServiceClient{cc}
}

func (c *googleCloudStorageServiceClient) Exists(ctx context.Context, in *GoogleCloudStorageExistsRequest, opts ...grpc.CallOption) (*GoogleCloudStorageExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleCloudStorageExistsResponse)
	err := c.cc.Invoke(ctx, GoogleCloudStorageService_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *googleCloudStorageServiceClient) Store(ctx context.Context, in *GoogleCloudStorageStoreRequest, opts ...grpc.CallOption) (*GoogleCloudStorageStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleCloudStorageStoreResponse)
	err := c.cc.Invoke(ctx, GoogleCloudStorageService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *googleCloudStorageServiceClient) CreateBucket(ctx context.Context, in *GoogleCloudStorageCreateBucketRequest, opts ...grpc.CallOption) (*GoogleCloudStorageCreateBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleCloudStorageCreateBucketResponse)
	err := c.cc.Invoke(ctx, GoogleCloudStorageService_CreateBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *googleCloudStorageServiceClient) GetBucket(ctx context.Context, in *GoogleCloudStorageGetBucketRequest, opts ...grpc.CallOption) (*GoogleCloudStorageGetBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleCloudStorageGetBucketResponse)
	err := c.cc.Invoke(ctx, GoogleCloudStorageService_GetBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *googleCloudStorageServiceClient) UpdateBucket(ctx context.Context, in *GoogleCloudStorageUpdateBucketRequest, opts ...grpc.CallOption) (*GoogleCloudStorageUpdateBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleCloudStorageUpdateBucketResponse)
	err := c.cc.Invoke(ctx, GoogleCloudStorageService_UpdateBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *googleCloudStorageServiceClient) DeleteBucket(ctx context.Context, in *GoogleCloudStorageDeleteBucketRequest, opts ...grpc.CallOption) (*GoogleCloudStorageDeleteBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleCloudStorageDeleteBucketResponse)
	err := c.cc.Invoke(ctx, GoogleCloudStorageService_DeleteBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *googleCloudStorageServiceClient) GetObject(ctx context.Context, in *GoogleCloudStorageGetObjectRequest, opts ...grpc.CallOption) (*GoogleCloudStorageGetObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleCloudStorageGetObjectResponse)
	err := c.cc.Invoke(ctx, GoogleCloudStorageService_GetObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *googleCloudStorageServiceClient) UpdateObjectMetadata(ctx context.Context, in *GoogleCloudStorageUpdateObjectMetadataRequest, opts ...grpc.CallOption) (*GoogleCloudStorageUpdateObjectMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleCloudStorageUpdateObjectMetadataResponse)
	err := c.cc.Invoke(ctx, GoogleCloudStorageService_UpdateObjectMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *googleCloudStorageServiceClient) DeleteObject(ctx context.Context, in *GoogleCloudStorageDeleteObjectRequest, opts ...grpc.CallOption) (*GoogleCloudStorageDeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleCloudStorageDeleteObjectResponse)
	err := c.cc.Invoke(ctx, GoogleCloudStorageService_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoogleCloudStorageServiceServer is the server API for GoogleCloudStorageService service.
// All implementations must embed UnimplementedGoogleCloudStorageServiceServer
// for forward compatibility.
type GoogleCloudStorageServiceServer interface {
	Exists(context.Context, *GoogleCloudStorageExistsRequest) (*GoogleCloudStorageExistsResponse, error)
	Store(context.Context, *GoogleCloudStorageStoreRequest) (*GoogleCloudStorageStoreResponse, error)
	CreateBucket(context.Context, *GoogleCloudStorageCreateBucketRequest) (*GoogleCloudStorageCreateBucketResponse, error)
	GetBucket(context.Context, *GoogleCloudStorageGetBucketRequest) (*GoogleCloudStorageGetBucketResponse, error)
	UpdateBucket(context.Context, *GoogleCloudStorageUpdateBucketRequest) (*GoogleCloudStorageUpdateBucketResponse, error)
	DeleteBucket(context.Context, *GoogleCloudStorageDeleteBucketRequest) (*GoogleCloudStorageDeleteBucketResponse, error)
	GetObject(context.Context, *GoogleCloudStorageGetObjectRequest) (*GoogleCloudStorageGetObjectResponse, error)
	UpdateObjectMetadata(context.Context, *GoogleCloudStorageUpdateObjectMetadataRequest) (*GoogleCloudStorageUpdateObjectMetadataResponse, error)
	DeleteObject(context.Context, *GoogleCloudStorageDeleteObjectRequest) (*GoogleCloudStorageDeleteObjectResponse, error)
	mustEmbedUnimplementedGoogleCloudStorageServiceServer()
}

// UnimplementedGoogleCloudStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoogleCloudStorageServiceServer struct{}

func (UnimplementedGoogleCloudStorageServiceServer) Exists(context.Context, *GoogleCloudStorageExistsRequest) (*GoogleCloudStorageExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedGoogleCloudStorageServiceServer) Store(context.Context, *GoogleCloudStorageStoreRequest) (*GoogleCloudStorageStoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedGoogleCloudStorageServiceServer) CreateBucket(context.Context, *GoogleCloudStorageCreateBucketRequest) (*GoogleCloudStorageCreateBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBucket not implemented")
}
func (UnimplementedGoogleCloudStorageServiceServer) GetBucket(context.Context, *GoogleCloudStorageGetBucketRequest) (*GoogleCloudStorageGetBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucket not implemented")
}
func (UnimplementedGoogleCloudStorageServiceServer) UpdateBucket(context.Context, *GoogleCloudStorageUpdateBucketRequest) (*GoogleCloudStorageUpdateBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBucket not implemented")
}
func (UnimplementedGoogleCloudStorageServiceServer) DeleteBucket(context.Context, *GoogleCloudStorageDeleteBucketRequest) (*GoogleCloudStorageDeleteBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (UnimplementedGoogleCloudStorageServiceServer) GetObject(context.Context, *GoogleCloudStorageGetObjectRequest) (*GoogleCloudStorageGetObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedGoogleCloudStorageServiceServer) UpdateObjectMetadata(context.Context, *GoogleCloudStorageUpdateObjectMetadataRequest) (*GoogleCloudStorageUpdateObjectMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateObjectMetadata not implemented")
}
func (UnimplementedGoogleCloudStorageServiceServer) DeleteObject(context.Context, *GoogleCloudStorageDeleteObjectRequest) (*GoogleCloudStorageDeleteObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedGoogleCloudStorageServiceServer) mustEmbedUnimplementedGoogleCloudStorageServiceServer() {
}
func (UnimplementedGoogleCloudStorageServiceServer) testEmbeddedByValue() {}

// UnsafeGoogleCloudStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoogleCloudStorageServiceServer will
// result in compilation errors.
type UnsafeGoogleCloudStorageServiceServer interface {
	mustEmbedUnimplementedGoogleCloudStorageServiceServer()
}

func RegisterGoogleCloudStorageServiceServer(s grpc.ServiceRegistrar, srv GoogleCloudStorageServiceServer) {
	// If the following call panics, it indicates UnimplementedGoogleCloudStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoogleCloudStorageService_ServiceDesc, srv)
}

func _GoogleCloudStorageService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleCloudStorageExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleCloudStorageServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleCloudStorageService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleCloudStorageServiceServer).Exists(ctx, req.(*GoogleCloudStorageExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoogleCloudStorageService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleCloudStorageStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleCloudStorageServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleCloudStorageService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleCloudStorageServiceServer).Store(ctx, req.(*GoogleCloudStorageStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoogleCloudStorageService_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleCloudStorageCreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleCloudStorageServiceServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleCloudStorageService_CreateBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleCloudStorageServiceServer).CreateBucket(ctx, req.(*GoogleCloudStorageCreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoogleCloudStorageService_GetBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleCloudStorageGetBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleCloudStorageServiceServer).GetBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleCloudStorageService_GetBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleCloudStorageServiceServer).GetBucket(ctx, req.(*GoogleCloudStorageGetBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoogleCloudStorageService_UpdateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleCloudStorageUpdateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleCloudStorageServiceServer).UpdateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleCloudStorageService_UpdateBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleCloudStorageServiceServer).UpdateBucket(ctx, req.(*GoogleCloudStorageUpdateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoogleCloudStorageService_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleCloudStorageDeleteBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleCloudStorageServiceServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleCloudStorageService_DeleteBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleCloudStorageServiceServer).DeleteBucket(ctx, req.(*GoogleCloudStorageDeleteBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoogleCloudStorageService_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleCloudStorageGetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleCloudStorageServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleCloudStorageService_GetObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleCloudStorageServiceServer).GetObject(ctx, req.(*GoogleCloudStorageGetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoogleCloudStorageService_UpdateObjectMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleCloudStorageUpdateObjectMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleCloudStorageServiceServer).UpdateObjectMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleCloudStorageService_UpdateObjectMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleCloudStorageServiceServer).UpdateObjectMetadata(ctx, req.(*GoogleCloudStorageUpdateObjectMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoogleCloudStorageService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleCloudStorageDeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleCloudStorageServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleCloudStorageService_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleCloudStorageServiceServer).DeleteObject(ctx, req.(*GoogleCloudStorageDeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoogleCloudStorageService_ServiceDesc is the grpc.ServiceDesc for GoogleCloudStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoogleCloudStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gist.GoogleCloudStorageService",
	HandlerType: (*GoogleCloudStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exists",
			Handler:    _GoogleCloudStorageService_Exists_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _GoogleCloudStorageService_Store_Handler,
		},
		{
			MethodName: "CreateBucket",
			Handler:    _GoogleCloudStorageService_CreateBucket_Handler,
		},
		{
			MethodName: "GetBucket",
			Handler:    _GoogleCloudStorageService_GetBucket_Handler,
		},
		{
			MethodName: "UpdateBucket",
			Handler:    _GoogleCloudStorageService_UpdateBucket_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _GoogleCloudStorageService_DeleteBucket_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _GoogleCloudStorageService_GetObject_Handler,
		},
		{
			MethodName: "UpdateObjectMetadata",
			Handler:    _GoogleCloudStorageService_UpdateObjectMetadata_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _GoogleCloudStorageService_DeleteObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gcs.proto",
}
