// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/httpclient.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HTTPClientService_Do_FullMethodName = "/gist.HTTPClientService/Do"
)

// HTTPClientServiceClient is the client API for HTTPClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HTTPClientServiceClient interface {
	Do(ctx context.Context, in *HTTPDoRequest, opts ...grpc.CallOption) (*HTTPDoResponse, error)
}

type hTTPClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHTTPClientServiceClient(cc grpc.ClientConnInterface) HTTPClientServiceClient {
	return &hTTPClientServiceClient{cc}
}

func (c *hTTPClientServiceClient) Do(ctx context.Context, in *HTTPDoRequest, opts ...grpc.CallOption) (*HTTPDoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPDoResponse)
	err := c.cc.Invoke(ctx, HTTPClientService_Do_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPClientServiceServer is the server API for HTTPClientService service.
// All implementations must embed UnimplementedHTTPClientServiceServer
// for forward compatibility.
type HTTPClientServiceServer interface {
	Do(context.Context, *HTTPDoRequest) (*HTTPDoResponse, error)
	mustEmbedUnimplementedHTTPClientServiceServer()
}

// UnimplementedHTTPClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHTTPClientServiceServer struct{}

func (UnimplementedHTTPClientServiceServer) Do(context.Context, *HTTPDoRequest) (*HTTPDoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedHTTPClientServiceServer) mustEmbedUnimplementedHTTPClientServiceServer() {}
func (UnimplementedHTTPClientServiceServer) testEmbeddedByValue()                           {}

// UnsafeHTTPClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HTTPClientServiceServer will
// result in compilation errors.
type UnsafeHTTPClientServiceServer interface {
	mustEmbedUnimplementedHTTPClientServiceServer()
}

func RegisterHTTPClientServiceServer(s grpc.ServiceRegistrar, srv HTTPClientServiceServer) {
	// If the following call panics, it indicates UnimplementedHTTPClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HTTPClientService_ServiceDesc, srv)
}

func _HTTPClientService_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPDoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPClientServiceServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPClientService_Do_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPClientServiceServer).Do(ctx, req.(*HTTPDoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HTTPClientService_ServiceDesc is the grpc.ServiceDesc for HTTPClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HTTPClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gist.HTTPClientService",
	HandlerType: (*HTTPClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _HTTPClientService_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/httpclient.proto",
}
