// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/httpclient.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HTTPClientService is a port of plugins/services/gist_http_client,
// moved fully server-side (unlike this port's first pass, which kept it
// client-side reasoning there was nothing to hide - the customer asked
// for consistency with every other service instead): the actual
// *http.Client, base URL, default headers, timeout, and TLS config all
// live in gist-server, hidden; the customer's process only ever sends
// one request's shape and gets back one response.
type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_proto_httpclient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_proto_httpclient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_proto_httpclient_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type HTTPDoRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceId           string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Method              string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url                 string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Headers             map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueryParams         map[string]string      `protobuf:"bytes,5,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body                []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	OmitResponseHeaders bool                   `protobuf:"varint,7,opt,name=omit_response_headers,json=omitResponseHeaders,proto3" json:"omit_response_headers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HTTPDoRequest) Reset() {
	*x = HTTPDoRequest{}
	mi := &file_proto_httpclient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPDoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPDoRequest) ProtoMessage() {}

func (x *HTTPDoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_httpclient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPDoRequest.ProtoReflect.Descriptor instead.
func (*HTTPDoRequest) Descriptor() ([]byte, []int) {
	return file_proto_httpclient_proto_rawDescGZIP(), []int{1}
}

func (x *HTTPDoRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *HTTPDoRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPDoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPDoRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPDoRequest) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *HTTPDoRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HTTPDoRequest) GetOmitResponseHeaders() bool {
	if x != nil {
		return x.OmitResponseHeaders
	}
	return false
}

type HTTPDoResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	StatusCode      int32                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ResponseHeaders map[string]*HeaderValues `protobuf:"bytes,2,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // preserves multi-value headers (e.g. multiple Set-Cookie) - a plain map<string,string> would lose that
	Body            []byte                   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ErrorMessage    string                   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // empty means success
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HTTPDoResponse) Reset() {
	*x = HTTPDoResponse{}
	mi := &file_proto_httpclient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPDoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPDoResponse) ProtoMessage() {}

func (x *HTTPDoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_httpclient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPDoResponse.ProtoReflect.Descriptor instead.
func (*HTTPDoResponse) Descriptor() ([]byte, []int) {
	return file_proto_httpclient_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPDoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HTTPDoResponse) GetResponseHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *HTTPDoResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HTTPDoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_httpclient_proto protoreflect.FileDescriptor

const file_proto_httpclient_proto_rawDesc = "" +
	"\n" +
	"\x16proto/httpclient.proto\x12\x04gist\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xa1\x03\n" +
	"\rHTTPDoRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12:\n" +
	"\aheaders\x18\x04 \x03(\v2 .gist.HTTPDoRequest.HeadersEntryR\aheaders\x12G\n" +
	"\fquery_params\x18\x05 \x03(\v2$.gist.HTTPDoRequest.QueryParamsEntryR\vqueryParams\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x122\n" +
	"\x15omit_response_headers\x18\a \x01(\bR\x13omitResponseHeaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x02\n" +
	"\x0eHTTPDoResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12T\n" +
	"\x10response_headers\x18\x02 \x03(\v2).gist.HTTPDoResponse.ResponseHeadersEntryR\x0fresponseHeaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x1aV\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.gist.HeaderValuesR\x05value:\x028\x012D\n" +
	"\x11HTTPClientService\x12/\n" +
	"\x02Do\x12\x13.gist.HTTPDoRequest\x1a\x14.gist.HTTPDoResponseB&Z$github.com/wieoapps/gist/proto;protob\x06proto3"

var (
	file_proto_httpclient_proto_rawDescOnce sync.Once
	file_proto_httpclient_proto_rawDescData []byte
)

func file_proto_httpclient_proto_rawDescGZIP() []byte {
	file_proto_httpclient_proto_rawDescOnce.Do(func() {
		file_proto_httpclient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_httpclient_proto_rawDesc), len(file_proto_httpclient_proto_rawDesc)))
	})
	return file_proto_httpclient_proto_rawDescData
}

var file_proto_httpclient_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_httpclient_proto_goTypes = []any{
	(*HeaderValues)(nil),   // 0: gist.HeaderValues
	(*HTTPDoRequest)(nil),  // 1: gist.HTTPDoRequest
	(*HTTPDoResponse)(nil), // 2: gist.HTTPDoResponse
	nil,                    // 3: gist.HTTPDoRequest.HeadersEntry
	nil,                    // 4: gist.HTTPDoRequest.QueryParamsEntry
	nil,                    // 5: gist.HTTPDoResponse.ResponseHeadersEntry
}
var file_proto_httpclient_proto_depIdxs = []int32{
	3, // 0: gist.HTTPDoRequest.headers:type_name -> gist.HTTPDoRequest.HeadersEntry
	4, // 1: gist.HTTPDoRequest.query_params:type_name -> gist.HTTPDoRequest.QueryParamsEntry
	5, // 2: gist.HTTPDoResponse.response_headers:type_name -> gist.HTTPDoResponse.ResponseHeadersEntry
	0, // 3: gist.HTTPDoResponse.ResponseHeadersEntry.value:type_name -> gist.HeaderValues
	1, // 4: gist.HTTPClientService.Do:input_type -> gist.HTTPDoRequest
	2, // 5: gist.HTTPClientService.Do:output_type -> gist.HTTPDoResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_httpclient_proto_init() }
func file_proto_httpclient_proto_init() {
	if File_proto_httpclient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_httpclient_proto_rawDesc), len(file_proto_httpclient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_httpclient_proto_goTypes,
		DependencyIndexes: file_proto_httpclient_proto_depIdxs,
		MessageInfos:      file_proto_httpclient_proto_msgTypes,
	}.Build()
	File_proto_httpclient_proto = out.File
	file_proto_httpclient_proto_goTypes = nil
	file_proto_httpclient_proto_depIdxs = nil
}
