// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/mysql.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_mysql_proto protoreflect.FileDescriptor

const file_proto_mysql_proto_rawDesc = "" +
	"\n" +
	"\x11proto/mysql.proto\x12\x04gist\x1a\x10proto/repo.proto2\xee\x01\n" +
	"\fMySQLService\x12Q\n" +
	"\x10BeginTransaction\x12\x1d.gist.BeginTransactionRequest\x1a\x1e.gist.BeginTransactionResponse\x12,\n" +
	"\x06Commit\x12\x17.gist.TransactionHandle\x1a\t.gist.Ack\x12.\n" +
	"\bRollback\x12\x17.gist.TransactionHandle\x1a\t.gist.Ack\x12-\n" +
	"\x04Repo\x12\x11.gist.RepoRequest\x1a\x12.gist.RepoResponseB&Z$github.com/wieoapps/gist/proto;protob\x06proto3"

var file_proto_mysql_proto_goTypes = []any{
	(*BeginTransactionRequest)(nil),  // 0: gist.BeginTransactionRequest
	(*TransactionHandle)(nil),        // 1: gist.TransactionHandle
	(*RepoRequest)(nil),              // 2: gist.RepoRequest
	(*BeginTransactionResponse)(nil), // 3: gist.BeginTransactionResponse
	(*Ack)(nil),                      // 4: gist.Ack
	(*RepoResponse)(nil),             // 5: gist.RepoResponse
}
var file_proto_mysql_proto_depIdxs = []int32{
	0, // 0: gist.MySQLService.BeginTransaction:input_type -> gist.BeginTransactionRequest
	1, // 1: gist.MySQLService.Commit:input_type -> gist.TransactionHandle
	1, // 2: gist.MySQLService.Rollback:input_type -> gist.TransactionHandle
	2, // 3: gist.MySQLService.Repo:input_type -> gist.RepoRequest
	3, // 4: gist.MySQLService.BeginTransaction:output_type -> gist.BeginTransactionResponse
	4, // 5: gist.MySQLService.Commit:output_type -> gist.Ack
	4, // 6: gist.MySQLService.Rollback:output_type -> gist.Ack
	5, // 7: gist.MySQLService.Repo:output_type -> gist.RepoResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mysql_proto_init() }
func file_proto_mysql_proto_init() {
	if File_proto_mysql_proto != nil {
		return
	}
	file_proto_repo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mysql_proto_rawDesc), len(file_proto_mysql_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mysql_proto_goTypes,
		DependencyIndexes: file_proto_mysql_proto_depIdxs,
	}.Build()
	File_proto_mysql_proto = out.File
	file_proto_mysql_proto_goTypes = nil
	file_proto_mysql_proto_depIdxs = nil
}
