// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/mysql.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MySQLService_BeginTransaction_FullMethodName = "/gist.MySQLService/BeginTransaction"
	MySQLService_Commit_FullMethodName           = "/gist.MySQLService/Commit"
	MySQLService_Rollback_FullMethodName         = "/gist.MySQLService/Rollback"
	MySQLService_Repo_FullMethodName             = "/gist.MySQLService/Repo"
)

// MySQLServiceClient is the client API for MySQLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MySQLService is served by gist-server and called by the customer's stub
// process for every gist-mysql query - the real connection pool and all
// SQL-building/scanning logic (the actual port of
// plugins/common/db/sql/repo) live entirely server-side; the client only
// ever sends a schema description, a condition tree, and gets back
// already-materialized JSON rows.
type MySQLServiceClient interface {
	BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error)
	Commit(ctx context.Context, in *TransactionHandle, opts ...grpc.CallOption) (*Ack, error)
	Rollback(ctx context.Context, in *TransactionHandle, opts ...grpc.CallOption) (*Ack, error)
	Repo(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*RepoResponse, error)
}

type mySQLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMySQLServiceClient(cc grpc.ClientConnInterface) MySQLServiceClient {
	return &mySQLServiceClient{cc}
}

func (c *mySQLServiceClient) BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTransactionResponse)
	err := c.cc.Invoke(ctx, MySQLService_BeginTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySQLServiceClient) Commit(ctx context.Context, in *TransactionHandle, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, MySQLService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySQLServiceClient) Rollback(ctx context.Context, in *TransactionHandle, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, MySQLService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySQLServiceClient) Repo(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*RepoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoResponse)
	err := c.cc.Invoke(ctx, MySQLService_Repo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MySQLServiceServer is the server API for MySQLService service.
// All implementations must embed UnimplementedMySQLServiceServer
// for forward compatibility.
//
// MySQLService is served by gist-server and called by the customer's stub
// process for every gist-mysql query - the real connection pool and all
// SQL-building/scanning logic (the actual port of
// plugins/common/db/sql/repo) live entirely server-side; the client only
// ever sends a schema description, a condition tree, and gets back
// already-materialized JSON rows.
type MySQLServiceServer interface {
	BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error)
	Commit(context.Context, *TransactionHandle) (*Ack, error)
	Rollback(context.Context, *TransactionHandle) (*Ack, error)
	Repo(context.Context, *RepoRequest) (*RepoResponse, error)
	mustEmbedUnimplementedMySQLServiceServer()
}

// UnimplementedMySQLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMySQLServiceServer struct{}

func (UnimplementedMySQLServiceServer) BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginTransaction not implemented")
}
func (UnimplementedMySQLServiceServer) Commit(context.Context, *TransactionHandle) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedMySQLServiceServer) Rollback(context.Context, *TransactionHandle) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedMySQLServiceServer) Repo(context.Context, *RepoRequest) (*RepoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Repo not implemented")
}
func (UnimplementedMySQLServiceServer) mustEmbedUnimplementedMySQLServiceServer() {}
func (UnimplementedMySQLServiceServer) testEmbeddedByValue()                      {}

// UnsafeMySQLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MySQLServiceServer will
// result in compilation errors.
type UnsafeMySQLServiceServer interface {
	mustEmbedUnimplementedMySQLServiceServer()
}

func RegisterMySQLServiceServer(s grpc.ServiceRegistrar, srv MySQLServiceServer) {
	// If the following call panics, it indicates UnimplementedMySQLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MySQLService_ServiceDesc, srv)
}

func _MySQLService_BeginTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLServiceServer).BeginTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MySQLService_BeginTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLServiceServer).BeginTransaction(ctx, req.(*BeginTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySQLService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MySQLService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLServiceServer).Commit(ctx, req.(*TransactionHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySQLService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MySQLService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLServiceServer).Rollback(ctx, req.(*TransactionHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySQLService_Repo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLServiceServer).Repo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MySQLService_Repo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLServiceServer).Repo(ctx, req.(*RepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MySQLService_ServiceDesc is the grpc.ServiceDesc for MySQLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MySQLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gist.MySQLService",
	HandlerType: (*MySQLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginTransaction",
			Handler:    _MySQLService_BeginTransaction_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _MySQLService_Commit_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _MySQLService_Rollback_Handler,
		},
		{
			MethodName: "Repo",
			Handler:    _MySQLService_Repo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mysql.proto",
}
