// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/postgres.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostgresService_BeginTransaction_FullMethodName = "/gist.PostgresService/BeginTransaction"
	PostgresService_Commit_FullMethodName           = "/gist.PostgresService/Commit"
	PostgresService_Rollback_FullMethodName         = "/gist.PostgresService/Rollback"
	PostgresService_Repo_FullMethodName             = "/gist.PostgresService/Repo"
)

// PostgresServiceClient is the client API for PostgresService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PostgresService is gist-postgres's exact counterpart to MySQLService -
// same message shapes (ModelSchema/Condition/QueryOptions/RepoRequest/
// RepoResponse are engine-agnostic; nothing about them is MySQL-
// specific), a separate rpc service only because one gRPC server can
// register just one implementation per service name, and gist-mysql and
// gist-postgres pools are never the same pool. Mirrors the original's
// own sql.Queryable interface being identical for both engines - the
// customer-facing repo.Find[model](tr, ...) call shape doesn't change
// depending on which database is actually behind tr.
type PostgresServiceClient interface {
	BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error)
	Commit(ctx context.Context, in *TransactionHandle, opts ...grpc.CallOption) (*Ack, error)
	Rollback(ctx context.Context, in *TransactionHandle, opts ...grpc.CallOption) (*Ack, error)
	Repo(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*RepoResponse, error)
}

type postgresServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostgresServiceClient(cc grpc.ClientConnInterface) PostgresServiceClient {
	return &postgresServiceClient{cc}
}

func (c *postgresServiceClient) BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTransactionResponse)
	err := c.cc.Invoke(ctx, PostgresService_BeginTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postgresServiceClient) Commit(ctx context.Context, in *TransactionHandle, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, PostgresService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postgresServiceClient) Rollback(ctx context.Context, in *TransactionHandle, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, PostgresService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postgresServiceClient) Repo(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*RepoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoResponse)
	err := c.cc.Invoke(ctx, PostgresService_Repo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostgresServiceServer is the server API for PostgresService service.
// All implementations must embed UnimplementedPostgresServiceServer
// for forward compatibility.
//
// PostgresService is gist-postgres's exact counterpart to MySQLService -
// same message shapes (ModelSchema/Condition/QueryOptions/RepoRequest/
// RepoResponse are engine-agnostic; nothing about them is MySQL-
// specific), a separate rpc service only because one gRPC server can
// register just one implementation per service name, and gist-mysql and
// gist-postgres pools are never the same pool. Mirrors the original's
// own sql.Queryable interface being identical for both engines - the
// customer-facing repo.Find[model](tr, ...) call shape doesn't change
// depending on which database is actually behind tr.
type PostgresServiceServer interface {
	BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error)
	Commit(context.Context, *TransactionHandle) (*Ack, error)
	Rollback(context.Context, *TransactionHandle) (*Ack, error)
	Repo(context.Context, *RepoRequest) (*RepoResponse, error)
	mustEmbedUnimplementedPostgresServiceServer()
}

// UnimplementedPostgresServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostgresServiceServer struct{}

func (UnimplementedPostgresServiceServer) BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginTransaction not implemented")
}
func (UnimplementedPostgresServiceServer) Commit(context.Context, *TransactionHandle) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedPostgresServiceServer) Rollback(context.Context, *TransactionHandle) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedPostgresServiceServer) Repo(context.Context, *RepoRequest) (*RepoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Repo not implemented")
}
func (UnimplementedPostgresServiceServer) mustEmbedUnimplementedPostgresServiceServer() {}
func (UnimplementedPostgresServiceServer) testEmbeddedByValue()                         {}

// UnsafePostgresServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostgresServiceServer will
// result in compilation errors.
type UnsafePostgresServiceServer interface {
	mustEmbedUnimplementedPostgresServiceServer()
}

func RegisterPostgresServiceServer(s grpc.ServiceRegistrar, srv PostgresServiceServer) {
	// If the following call panics, it indicates UnimplementedPostgresServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostgresService_ServiceDesc, srv)
}

func _PostgresService_BeginTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgresServiceServer).BeginTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostgresService_BeginTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgresServiceServer).BeginTransaction(ctx, req.(*BeginTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostgresService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgresServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostgresService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgresServiceServer).Commit(ctx, req.(*TransactionHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostgresService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgresServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostgresService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgresServiceServer).Rollback(ctx, req.(*TransactionHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostgresService_Repo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgresServiceServer).Repo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostgresService_Repo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgresServiceServer).Repo(ctx, req.(*RepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostgresService_ServiceDesc is the grpc.ServiceDesc for PostgresService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostgresService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gist.PostgresService",
	HandlerType: (*PostgresServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginTransaction",
			Handler:    _PostgresService_BeginTransaction_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _PostgresService_Commit_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _PostgresService_Rollback_Handler,
		},
		{
			MethodName: "Repo",
			Handler:    _PostgresService_Repo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/postgres.proto",
}
