// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/rabbitmq.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RabbitMQService_Publish_FullMethodName         = "/gist.RabbitMQService/Publish"
	RabbitMQService_ExchangeDeclare_FullMethodName = "/gist.RabbitMQService/ExchangeDeclare"
	RabbitMQService_QueueDeclare_FullMethodName    = "/gist.RabbitMQService/QueueDeclare"
	RabbitMQService_QueueBind_FullMethodName       = "/gist.RabbitMQService/QueueBind"
	RabbitMQService_StartConsuming_FullMethodName  = "/gist.RabbitMQService/StartConsuming"
)

// RabbitMQServiceClient is the client API for RabbitMQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RabbitMQServiceClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	ExchangeDeclare(ctx context.Context, in *ExchangeDeclareRequest, opts ...grpc.CallOption) (*ExchangeDeclareResponse, error)
	QueueDeclare(ctx context.Context, in *QueueDeclareRequest, opts ...grpc.CallOption) (*QueueDeclareResponse, error)
	QueueBind(ctx context.Context, in *QueueBindRequest, opts ...grpc.CallOption) (*QueueBindResponse, error)
	StartConsuming(ctx context.Context, in *StartConsumingRequest, opts ...grpc.CallOption) (*StartConsumingResponse, error)
}

type rabbitMQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRabbitMQServiceClient(cc grpc.ClientConnInterface) RabbitMQServiceClient {
	return &rabbitMQServiceClient{cc}
}

func (c *rabbitMQServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, RabbitMQService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rabbitMQServiceClient) ExchangeDeclare(ctx context.Context, in *ExchangeDeclareRequest, opts ...grpc.CallOption) (*ExchangeDeclareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeDeclareResponse)
	err := c.cc.Invoke(ctx, RabbitMQService_ExchangeDeclare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rabbitMQServiceClient) QueueDeclare(ctx context.Context, in *QueueDeclareRequest, opts ...grpc.CallOption) (*QueueDeclareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueDeclareResponse)
	err := c.cc.Invoke(ctx, RabbitMQService_QueueDeclare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rabbitMQServiceClient) QueueBind(ctx context.Context, in *QueueBindRequest, opts ...grpc.CallOption) (*QueueBindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueBindResponse)
	err := c.cc.Invoke(ctx, RabbitMQService_QueueBind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rabbitMQServiceClient) StartConsuming(ctx context.Context, in *StartConsumingRequest, opts ...grpc.CallOption) (*StartConsumingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartConsumingResponse)
	err := c.cc.Invoke(ctx, RabbitMQService_StartConsuming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RabbitMQServiceServer is the server API for RabbitMQService service.
// All implementations must embed UnimplementedRabbitMQServiceServer
// for forward compatibility.
type RabbitMQServiceServer interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	ExchangeDeclare(context.Context, *ExchangeDeclareRequest) (*ExchangeDeclareResponse, error)
	QueueDeclare(context.Context, *QueueDeclareRequest) (*QueueDeclareResponse, error)
	QueueBind(context.Context, *QueueBindRequest) (*QueueBindResponse, error)
	StartConsuming(context.Context, *StartConsumingRequest) (*StartConsumingResponse, error)
	mustEmbedUnimplementedRabbitMQServiceServer()
}

// UnimplementedRabbitMQServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRabbitMQServiceServer struct{}

func (UnimplementedRabbitMQServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedRabbitMQServiceServer) ExchangeDeclare(context.Context, *ExchangeDeclareRequest) (*ExchangeDeclareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeDeclare not implemented")
}
func (UnimplementedRabbitMQServiceServer) QueueDeclare(context.Context, *QueueDeclareRequest) (*QueueDeclareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueueDeclare not implemented")
}
func (UnimplementedRabbitMQServiceServer) QueueBind(context.Context, *QueueBindRequest) (*QueueBindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueueBind not implemented")
}
func (UnimplementedRabbitMQServiceServer) StartConsuming(context.Context, *StartConsumingRequest) (*StartConsumingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartConsuming not implemented")
}
func (UnimplementedRabbitMQServiceServer) mustEmbedUnimplementedRabbitMQServiceServer() {}
func (UnimplementedRabbitMQServiceServer) testEmbeddedByValue()                         {}

// UnsafeRabbitMQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RabbitMQServiceServer will
// result in compilation errors.
type UnsafeRabbitMQServiceServer interface {
	mustEmbedUnimplementedRabbitMQServiceServer()
}

func RegisterRabbitMQServiceServer(s grpc.ServiceRegistrar, srv RabbitMQServiceServer) {
	// If the following call panics, it indicates UnimplementedRabbitMQServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RabbitMQService_ServiceDesc, srv)
}

func _RabbitMQService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RabbitMQService_ExchangeDeclare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeDeclareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQServiceServer).ExchangeDeclare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQService_ExchangeDeclare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQServiceServer).ExchangeDeclare(ctx, req.(*ExchangeDeclareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RabbitMQService_QueueDeclare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueDeclareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQServiceServer).QueueDeclare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQService_QueueDeclare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQServiceServer).QueueDeclare(ctx, req.(*QueueDeclareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RabbitMQService_QueueBind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQServiceServer).QueueBind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQService_QueueBind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQServiceServer).QueueBind(ctx, req.(*QueueBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RabbitMQService_StartConsuming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartConsumingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQServiceServer).StartConsuming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQService_StartConsuming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQServiceServer).StartConsuming(ctx, req.(*StartConsumingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RabbitMQService_ServiceDesc is the grpc.ServiceDesc for RabbitMQService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RabbitMQService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gist.RabbitMQService",
	HandlerType: (*RabbitMQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _RabbitMQService_Publish_Handler,
		},
		{
			MethodName: "ExchangeDeclare",
			Handler:    _RabbitMQService_ExchangeDeclare_Handler,
		},
		{
			MethodName: "QueueDeclare",
			Handler:    _RabbitMQService_QueueDeclare_Handler,
		},
		{
			MethodName: "QueueBind",
			Handler:    _RabbitMQService_QueueBind_Handler,
		},
		{
			MethodName: "StartConsuming",
			Handler:    _RabbitMQService_StartConsuming_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rabbitmq.proto",
}
