// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/rabbitmq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RabbitMQService is served by gist-server and called by the customer's
// stub process - the connection and the real amqp091-go client live
// entirely server-side; the customer only ever sends already-JSON-
// encoded/opaque bytes and gets the same back, the same split every
// other real-operation service (Elasticsearch, GoogleCloudStorage) here
// already uses. Every RPC routes by service_id, the same config.json
// entry-id convention every other multi-instance admin server in this
// project uses.
//
// Declare args (ExchangeDeclare/QueueDeclare's `args`) are string-only,
// not the full AMQP table type (which allows ints/bools/nested tables) -
// a deliberate first-pass simplification. A caller needing a typed arg
// (e.g. `x-message-ttl` as an integer) passes its string form; gist-server
// parses it back to the type RabbitMQ's own arg actually expects before
// calling amqp091-go.
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"` // empty publishes to the default exchange (routing_key = queue name)
	RoutingKey    string                 `protobuf:"bytes,3,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // e.g. "application/json" - empty is fine, RabbitMQ doesn't require it
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Mandatory     bool                   `protobuf:"varint,7,opt,name=mandatory,proto3" json:"mandatory,omitempty"` // true: the broker reports back (as a publish error) if no queue can route it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_rabbitmq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rabbitmq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_rabbitmq_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *PublishRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PublishRequest) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *PublishRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PublishRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PublishRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PublishRequest) GetMandatory() bool {
	if x != nil {
		return x.Mandatory
	}
	return false
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_rabbitmq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rabbitmq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_rabbitmq_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PublishResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExchangeDeclareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // "direct" | "fanout" | "topic" | "headers"
	Durable       bool                   `protobuf:"varint,4,opt,name=durable,proto3" json:"durable,omitempty"`
	AutoDelete    bool                   `protobuf:"varint,5,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`
	Args          map[string]string      `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeDeclareRequest) Reset() {
	*x = ExchangeDeclareRequest{}
	mi := &file_proto_rabbitmq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeDeclareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeDeclareRequest) ProtoMessage() {}

func (x *ExchangeDeclareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rabbitmq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeDeclareRequest.ProtoReflect.Descriptor instead.
func (*ExchangeDeclareRequest) Descriptor() ([]byte, []int) {
	return file_proto_rabbitmq_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeDeclareRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ExchangeDeclareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExchangeDeclareRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExchangeDeclareRequest) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *ExchangeDeclareRequest) GetAutoDelete() bool {
	if x != nil {
		return x.AutoDelete
	}
	return false
}

func (x *ExchangeDeclareRequest) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ExchangeDeclareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeDeclareResponse) Reset() {
	*x = ExchangeDeclareResponse{}
	mi := &file_proto_rabbitmq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeDeclareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeDeclareResponse) ProtoMessage() {}

func (x *ExchangeDeclareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rabbitmq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeDeclareResponse.ProtoReflect.Descriptor instead.
func (*ExchangeDeclareResponse) Descriptor() ([]byte, []int) {
	return file_proto_rabbitmq_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeDeclareResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ExchangeDeclareResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type QueueDeclareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // empty lets the broker generate one - see QueueDeclareResponse.name
	Durable       bool                   `protobuf:"varint,3,opt,name=durable,proto3" json:"durable,omitempty"`
	AutoDelete    bool                   `protobuf:"varint,4,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`
	Exclusive     bool                   `protobuf:"varint,5,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	Args          map[string]string      `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueDeclareRequest) Reset() {
	*x = QueueDeclareRequest{}
	mi := &file_proto_rabbitmq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueDeclareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueDeclareRequest) ProtoMessage() {}

func (x *QueueDeclareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rabbitmq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueDeclareRequest.ProtoReflect.Descriptor instead.
func (*QueueDeclareRequest) Descriptor() ([]byte, []int) {
	return file_proto_rabbitmq_proto_rawDescGZIP(), []int{4}
}

func (x *QueueDeclareRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *QueueDeclareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueDeclareRequest) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *QueueDeclareRequest) GetAutoDelete() bool {
	if x != nil {
		return x.AutoDelete
	}
	return false
}

func (x *QueueDeclareRequest) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *QueueDeclareRequest) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type QueueDeclareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // the queue's real name - only differs from the request's when that was empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueDeclareResponse) Reset() {
	*x = QueueDeclareResponse{}
	mi := &file_proto_rabbitmq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueDeclareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueDeclareResponse) ProtoMessage() {}

func (x *QueueDeclareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rabbitmq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueDeclareResponse.ProtoReflect.Descriptor instead.
func (*QueueDeclareResponse) Descriptor() ([]byte, []int) {
	return file_proto_rabbitmq_proto_rawDescGZIP(), []int{5}
}

func (x *QueueDeclareResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *QueueDeclareResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *QueueDeclareResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueueBindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Exchange      string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	RoutingKey    string                 `protobuf:"bytes,4,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	Args          map[string]string      `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueBindRequest) Reset() {
	*x = QueueBindRequest{}
	mi := &file_proto_rabbitmq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueBindRequest) ProtoMessage() {}

func (x *QueueBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rabbitmq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueBindRequest.ProtoReflect.Descriptor instead.
func (*QueueBindRequest) Descriptor() ([]byte, []int) {
	return file_proto_rabbitmq_proto_rawDescGZIP(), []int{6}
}

func (x *QueueBindRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *QueueBindRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *QueueBindRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *QueueBindRequest) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *QueueBindRequest) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type QueueBindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueBindResponse) Reset() {
	*x = QueueBindResponse{}
	mi := &file_proto_rabbitmq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueBindResponse) ProtoMessage() {}

func (x *QueueBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rabbitmq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueBindResponse.ProtoReflect.Descriptor instead.
func (*QueueBindResponse) Descriptor() ([]byte, []int) {
	return file_proto_rabbitmq_proto_rawDescGZIP(), []int{7}
}

func (x *QueueBindResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *QueueBindResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// StartConsumingRequest activates a live delivery loop for queue on
// gist-server's own channel - one loop per (service_id, queue), started
// at most once (a second call for the same pair is a no-op, not an
// error, tolerating the same "customer process restarted its Option
// application" case StartCustomService already tolerates). Every
// delivery received after this call is pushed to the customer's process
// via CallbackService.Deliver (see callback.proto) - gist-server never
// runs the customer's own message-handling logic itself, the same
// "always runs in the customer's own process" rule every other callback
// here follows.
// auto_ack = false pairs with callback.proto's DeliverAck: gist-server
// calls the customer's CallbackService.Deliver synchronously for each
// message and, once that call returns, applies DeliverAck's own ack/
// requeue verdict to the same channel right there in the consume loop -
// there is deliberately no separate Ack/Nack RPC on this service. The
// delivery is never widowed from its outcome across two independent
// RPCs; the trade-off is that a customer wanting to defer acking past
// Deliver's own return (e.g. ack only after a slow async job finishes)
// isn't supported by this first pass.
type StartConsumingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	AutoAck       bool                   `protobuf:"varint,3,opt,name=auto_ack,json=autoAck,proto3" json:"auto_ack,omitempty"` // true: gist-server acks on delivery, before Deliver even runs - simpler, but a customer-side crash mid-handling silently drops the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartConsumingRequest) Reset() {
	*x = StartConsumingRequest{}
	mi := &file_proto_rabbitmq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartConsumingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConsumingRequest) ProtoMessage() {}

func (x *StartConsumingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rabbitmq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConsumingRequest.ProtoReflect.Descriptor instead.
func (*StartConsumingRequest) Descriptor() ([]byte, []int) {
	return file_proto_rabbitmq_proto_rawDescGZIP(), []int{8}
}

func (x *StartConsumingRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *StartConsumingRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *StartConsumingRequest) GetAutoAck() bool {
	if x != nil {
		return x.AutoAck
	}
	return false
}

type StartConsumingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartConsumingResponse) Reset() {
	*x = StartConsumingResponse{}
	mi := &file_proto_rabbitmq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartConsumingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConsumingResponse) ProtoMessage() {}

func (x *StartConsumingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rabbitmq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConsumingResponse.ProtoReflect.Descriptor instead.
func (*StartConsumingResponse) Descriptor() ([]byte, []int) {
	return file_proto_rabbitmq_proto_rawDescGZIP(), []int{9}
}

func (x *StartConsumingResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *StartConsumingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_rabbitmq_proto protoreflect.FileDescriptor

const file_proto_rabbitmq_proto_rawDesc = "" +
	"\n" +
	"\x14proto/rabbitmq.proto\x12\x04gist\"\xba\x02\n" +
	"\x0ePublishRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x1f\n" +
	"\vrouting_key\x18\x03 \x01(\tR\n" +
	"routingKey\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12;\n" +
	"\aheaders\x18\x06 \x03(\v2!.gist.PublishRequest.HeadersEntryR\aheaders\x12\x1c\n" +
	"\tmandatory\x18\a \x01(\bR\tmandatory\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x0fPublishResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x8f\x02\n" +
	"\x16ExchangeDeclareRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\adurable\x18\x04 \x01(\bR\adurable\x12\x1f\n" +
	"\vauto_delete\x18\x05 \x01(\bR\n" +
	"autoDelete\x12:\n" +
	"\x04args\x18\x06 \x03(\v2&.gist.ExchangeDeclareRequest.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x17ExchangeDeclareResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x93\x02\n" +
	"\x13QueueDeclareRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\adurable\x18\x03 \x01(\bR\adurable\x12\x1f\n" +
	"\vauto_delete\x18\x04 \x01(\bR\n" +
	"autoDelete\x12\x1c\n" +
	"\texclusive\x18\x05 \x01(\bR\texclusive\x127\n" +
	"\x04args\x18\x06 \x03(\v2#.gist.QueueDeclareRequest.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x14QueueDeclareResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xf3\x01\n" +
	"\x10QueueBindRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x1f\n" +
	"\vrouting_key\x18\x04 \x01(\tR\n" +
	"routingKey\x124\n" +
	"\x04args\x18\x05 \x03(\v2 .gist.QueueBindRequest.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x11QueueBindResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"g\n" +
	"\x15StartConsumingRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x19\n" +
	"\bauto_ack\x18\x03 \x01(\bR\aautoAck\"\\\n" +
	"\x16StartConsumingResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xeb\x02\n" +
	"\x0fRabbitMQService\x126\n" +
	"\aPublish\x12\x14.gist.PublishRequest\x1a\x15.gist.PublishResponse\x12N\n" +
	"\x0fExchangeDeclare\x12\x1c.gist.ExchangeDeclareRequest\x1a\x1d.gist.ExchangeDeclareResponse\x12E\n" +
	"\fQueueDeclare\x12\x19.gist.QueueDeclareRequest\x1a\x1a.gist.QueueDeclareResponse\x12<\n" +
	"\tQueueBind\x12\x16.gist.QueueBindRequest\x1a\x17.gist.QueueBindResponse\x12K\n" +
	"\x0eStartConsuming\x12\x1b.gist.StartConsumingRequest\x1a\x1c.gist.StartConsumingResponseB&Z$github.com/wieoapps/gist/proto;protob\x06proto3"

var (
	file_proto_rabbitmq_proto_rawDescOnce sync.Once
	file_proto_rabbitmq_proto_rawDescData []byte
)

func file_proto_rabbitmq_proto_rawDescGZIP() []byte {
	file_proto_rabbitmq_proto_rawDescOnce.Do(func() {
		file_proto_rabbitmq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rabbitmq_proto_rawDesc), len(file_proto_rabbitmq_proto_rawDesc)))
	})
	return file_proto_rabbitmq_proto_rawDescData
}

var file_proto_rabbitmq_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_rabbitmq_proto_goTypes = []any{
	(*PublishRequest)(nil),          // 0: gist.PublishRequest
	(*PublishResponse)(nil),         // 1: gist.PublishResponse
	(*ExchangeDeclareRequest)(nil),  // 2: gist.ExchangeDeclareRequest
	(*ExchangeDeclareResponse)(nil), // 3: gist.ExchangeDeclareResponse
	(*QueueDeclareRequest)(nil),     // 4: gist.QueueDeclareRequest
	(*QueueDeclareResponse)(nil),    // 5: gist.QueueDeclareResponse
	(*QueueBindRequest)(nil),        // 6: gist.QueueBindRequest
	(*QueueBindResponse)(nil),       // 7: gist.QueueBindResponse
	(*StartConsumingRequest)(nil),   // 8: gist.StartConsumingRequest
	(*StartConsumingResponse)(nil),  // 9: gist.StartConsumingResponse
	nil,                             // 10: gist.PublishRequest.HeadersEntry
	nil,                             // 11: gist.ExchangeDeclareRequest.ArgsEntry
	nil,                             // 12: gist.QueueDeclareRequest.ArgsEntry
	nil,                             // 13: gist.QueueBindRequest.ArgsEntry
}
var file_proto_rabbitmq_proto_depIdxs = []int32{
	10, // 0: gist.PublishRequest.headers:type_name -> gist.PublishRequest.HeadersEntry
	11, // 1: gist.ExchangeDeclareRequest.args:type_name -> gist.ExchangeDeclareRequest.ArgsEntry
	12, // 2: gist.QueueDeclareRequest.args:type_name -> gist.QueueDeclareRequest.ArgsEntry
	13, // 3: gist.QueueBindRequest.args:type_name -> gist.QueueBindRequest.ArgsEntry
	0,  // 4: gist.RabbitMQService.Publish:input_type -> gist.PublishRequest
	2,  // 5: gist.RabbitMQService.ExchangeDeclare:input_type -> gist.ExchangeDeclareRequest
	4,  // 6: gist.RabbitMQService.QueueDeclare:input_type -> gist.QueueDeclareRequest
	6,  // 7: gist.RabbitMQService.QueueBind:input_type -> gist.QueueBindRequest
	8,  // 8: gist.RabbitMQService.StartConsuming:input_type -> gist.StartConsumingRequest
	1,  // 9: gist.RabbitMQService.Publish:output_type -> gist.PublishResponse
	3,  // 10: gist.RabbitMQService.ExchangeDeclare:output_type -> gist.ExchangeDeclareResponse
	5,  // 11: gist.RabbitMQService.QueueDeclare:output_type -> gist.QueueDeclareResponse
	7,  // 12: gist.RabbitMQService.QueueBind:output_type -> gist.QueueBindResponse
	9,  // 13: gist.RabbitMQService.StartConsuming:output_type -> gist.StartConsumingResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_rabbitmq_proto_init() }
func file_proto_rabbitmq_proto_init() {
	if File_proto_rabbitmq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rabbitmq_proto_rawDesc), len(file_proto_rabbitmq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rabbitmq_proto_goTypes,
		DependencyIndexes: file_proto_rabbitmq_proto_depIdxs,
		MessageInfos:      file_proto_rabbitmq_proto_msgTypes,
	}.Build()
	File_proto_rabbitmq_proto = out.File
	file_proto_rabbitmq_proto_goTypes = nil
	file_proto_rabbitmq_proto_depIdxs = nil
}
