// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/redis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_redis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"` // false: key didn't exist - distinct from a genuinely empty value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_redis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 means no expiry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_proto_redis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_proto_redis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{3}
}

func (x *SetResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_proto_redis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{4}
}

func (x *DelRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DelRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Deleted       int64                  `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"` // number of keys actually removed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	mi := &file_proto_redis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{5}
}

func (x *DelResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DelResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DelResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

type ExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsRequest) Reset() {
	*x = ExistsRequest{}
	mi := &file_proto_redis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsRequest) ProtoMessage() {}

func (x *ExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsRequest.ProtoReflect.Descriptor instead.
func (*ExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{6}
}

func (x *ExistsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ExistsRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // how many of the given keys exist - a repeated key counts twice, matching Redis's own EXISTS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_proto_redis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{7}
}

func (x *ExistsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ExistsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExistsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type IncrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrRequest) Reset() {
	*x = IncrRequest{}
	mi := &file_proto_redis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrRequest) ProtoMessage() {}

func (x *IncrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrRequest.ProtoReflect.Descriptor instead.
func (*IncrRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{8}
}

func (x *IncrRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *IncrRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IncrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"` // the key's new value after incrementing by 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrResponse) Reset() {
	*x = IncrResponse{}
	mi := &file_proto_redis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrResponse) ProtoMessage() {}

func (x *IncrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrResponse.ProtoReflect.Descriptor instead.
func (*IncrResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{9}
}

func (x *IncrResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *IncrResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *IncrResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type IncrByRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	By            int64                  `protobuf:"varint,3,opt,name=by,proto3" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrByRequest) Reset() {
	*x = IncrByRequest{}
	mi := &file_proto_redis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrByRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrByRequest) ProtoMessage() {}

func (x *IncrByRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrByRequest.ProtoReflect.Descriptor instead.
func (*IncrByRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{10}
}

func (x *IncrByRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *IncrByRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IncrByRequest) GetBy() int64 {
	if x != nil {
		return x.By
	}
	return 0
}

type IncrByResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"` // the key's new value after incrementing by "by"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrByResponse) Reset() {
	*x = IncrByResponse{}
	mi := &file_proto_redis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrByResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrByResponse) ProtoMessage() {}

func (x *IncrByResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrByResponse.ProtoReflect.Descriptor instead.
func (*IncrByResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{11}
}

func (x *IncrByResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *IncrByResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *IncrByResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ExpireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireRequest) Reset() {
	*x = ExpireRequest{}
	mi := &file_proto_redis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireRequest) ProtoMessage() {}

func (x *ExpireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireRequest.ProtoReflect.Descriptor instead.
func (*ExpireRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{12}
}

func (x *ExpireRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ExpireRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExpireRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ExpireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Existed       bool                   `protobuf:"varint,3,opt,name=existed,proto3" json:"existed,omitempty"` // false: key didn't exist, so there was nothing to set a TTL on
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireResponse) Reset() {
	*x = ExpireResponse{}
	mi := &file_proto_redis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireResponse) ProtoMessage() {}

func (x *ExpireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireResponse.ProtoReflect.Descriptor instead.
func (*ExpireResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{13}
}

func (x *ExpireResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ExpireResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExpireResponse) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

var File_proto_redis_proto protoreflect.FileDescriptor

const file_proto_redis_proto_rawDesc = "" +
	"\n" +
	"\x11proto/redis.proto\x12\x04gist\"=\n" +
	"\n" +
	"GetRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"}\n" +
	"\vGetResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\"t\n" +
	"\n" +
	"SetRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\"Q\n" +
	"\vSetResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"?\n" +
	"\n" +
	"DelRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"k\n" +
	"\vDelResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\x03R\adeleted\"B\n" +
	"\rExistsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"j\n" +
	"\x0eExistsResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\">\n" +
	"\vIncrRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"h\n" +
	"\fIncrResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\"P\n" +
	"\rIncrByRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x0e\n" +
	"\x02by\x18\x03 \x01(\x03R\x02by\"j\n" +
	"\x0eIncrByResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\"a\n" +
	"\rExpireRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"n\n" +
	"\x0eExpireResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\aexisted\x18\x03 \x01(\bR\aexisted2\xe0\x02\n" +
	"\fRedisService\x12*\n" +
	"\x03Get\x12\x10.gist.GetRequest\x1a\x11.gist.GetResponse\x12*\n" +
	"\x03Set\x12\x10.gist.SetRequest\x1a\x11.gist.SetResponse\x12*\n" +
	"\x03Del\x12\x10.gist.DelRequest\x1a\x11.gist.DelResponse\x123\n" +
	"\x06Exists\x12\x13.gist.ExistsRequest\x1a\x14.gist.ExistsResponse\x12-\n" +
	"\x04Incr\x12\x11.gist.IncrRequest\x1a\x12.gist.IncrResponse\x123\n" +
	"\x06IncrBy\x12\x13.gist.IncrByRequest\x1a\x14.gist.IncrByResponse\x123\n" +
	"\x06Expire\x12\x13.gist.ExpireRequest\x1a\x14.gist.ExpireResponseB&Z$github.com/wieoapps/gist/proto;protob\x06proto3"

var (
	file_proto_redis_proto_rawDescOnce sync.Once
	file_proto_redis_proto_rawDescData []byte
)

func file_proto_redis_proto_rawDescGZIP() []byte {
	file_proto_redis_proto_rawDescOnce.Do(func() {
		file_proto_redis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_redis_proto_rawDesc), len(file_proto_redis_proto_rawDesc)))
	})
	return file_proto_redis_proto_rawDescData
}

var file_proto_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_redis_proto_goTypes = []any{
	(*GetRequest)(nil),     // 0: gist.GetRequest
	(*GetResponse)(nil),    // 1: gist.GetResponse
	(*SetRequest)(nil),     // 2: gist.SetRequest
	(*SetResponse)(nil),    // 3: gist.SetResponse
	(*DelRequest)(nil),     // 4: gist.DelRequest
	(*DelResponse)(nil),    // 5: gist.DelResponse
	(*ExistsRequest)(nil),  // 6: gist.ExistsRequest
	(*ExistsResponse)(nil), // 7: gist.ExistsResponse
	(*IncrRequest)(nil),    // 8: gist.IncrRequest
	(*IncrResponse)(nil),   // 9: gist.IncrResponse
	(*IncrByRequest)(nil),  // 10: gist.IncrByRequest
	(*IncrByResponse)(nil), // 11: gist.IncrByResponse
	(*ExpireRequest)(nil),  // 12: gist.ExpireRequest
	(*ExpireResponse)(nil), // 13: gist.ExpireResponse
}
var file_proto_redis_proto_depIdxs = []int32{
	0,  // 0: gist.RedisService.Get:input_type -> gist.GetRequest
	2,  // 1: gist.RedisService.Set:input_type -> gist.SetRequest
	4,  // 2: gist.RedisService.Del:input_type -> gist.DelRequest
	6,  // 3: gist.RedisService.Exists:input_type -> gist.ExistsRequest
	8,  // 4: gist.RedisService.Incr:input_type -> gist.IncrRequest
	10, // 5: gist.RedisService.IncrBy:input_type -> gist.IncrByRequest
	12, // 6: gist.RedisService.Expire:input_type -> gist.ExpireRequest
	1,  // 7: gist.RedisService.Get:output_type -> gist.GetResponse
	3,  // 8: gist.RedisService.Set:output_type -> gist.SetResponse
	5,  // 9: gist.RedisService.Del:output_type -> gist.DelResponse
	7,  // 10: gist.RedisService.Exists:output_type -> gist.ExistsResponse
	9,  // 11: gist.RedisService.Incr:output_type -> gist.IncrResponse
	11, // 12: gist.RedisService.IncrBy:output_type -> gist.IncrByResponse
	13, // 13: gist.RedisService.Expire:output_type -> gist.ExpireResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_redis_proto_init() }
func file_proto_redis_proto_init() {
	if File_proto_redis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_redis_proto_rawDesc), len(file_proto_redis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_redis_proto_goTypes,
		DependencyIndexes: file_proto_redis_proto_depIdxs,
		MessageInfos:      file_proto_redis_proto_msgTypes,
	}.Build()
	File_proto_redis_proto = out.File
	file_proto_redis_proto_goTypes = nil
	file_proto_redis_proto_depIdxs = nil
}
