// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/repo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepoOp int32

const (
	RepoOp_REPO_OP_UNSPECIFIED   RepoOp = 0
	RepoOp_FIND                  RepoOp = 1
	RepoOp_FIND_ONE              RepoOp = 2
	RepoOp_COUNT                 RepoOp = 3
	RepoOp_EXISTS                RepoOp = 4
	RepoOp_SAVE                  RepoOp = 5
	RepoOp_SAVE_WITH_RETURNING   RepoOp = 6
	RepoOp_UPDATE                RepoOp = 7
	RepoOp_UPDATE_WITH_RETURNING RepoOp = 8
	RepoOp_DELETE                RepoOp = 9
	RepoOp_DELETE_WITH_RETURNING RepoOp = 10
)

// Enum value maps for RepoOp.
var (
	RepoOp_name = map[int32]string{
		0:  "REPO_OP_UNSPECIFIED",
		1:  "FIND",
		2:  "FIND_ONE",
		3:  "COUNT",
		4:  "EXISTS",
		5:  "SAVE",
		6:  "SAVE_WITH_RETURNING",
		7:  "UPDATE",
		8:  "UPDATE_WITH_RETURNING",
		9:  "DELETE",
		10: "DELETE_WITH_RETURNING",
	}
	RepoOp_value = map[string]int32{
		"REPO_OP_UNSPECIFIED":   0,
		"FIND":                  1,
		"FIND_ONE":              2,
		"COUNT":                 3,
		"EXISTS":                4,
		"SAVE":                  5,
		"SAVE_WITH_RETURNING":   6,
		"UPDATE":                7,
		"UPDATE_WITH_RETURNING": 8,
		"DELETE":                9,
		"DELETE_WITH_RETURNING": 10,
	}
)

func (x RepoOp) Enum() *RepoOp {
	p := new(RepoOp)
	*p = x
	return p
}

func (x RepoOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepoOp) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_repo_proto_enumTypes[0].Descriptor()
}

func (RepoOp) Type() protoreflect.EnumType {
	return &file_proto_repo_proto_enumTypes[0]
}

func (x RepoOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepoOp.Descriptor instead.
func (RepoOp) EnumDescriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{0}
}

// EndAction is EndTransaction's requested close action - see EndTransaction
// below. UNSPECIFIED is rejected by the server (invalid_argument) rather
// than defaulted to either commit or rollback, since guessing here is
// exactly the ambiguity that ruled out auto-closing transactions server-side.
type EndAction int32

const (
	EndAction_END_ACTION_UNSPECIFIED  EndAction = 0
	EndAction_END_ACTION_ROLLBACK     EndAction = 1
	EndAction_END_ACTION_COMMIT       EndAction = 2
	EndAction_END_ACTION_COMMIT_IF_OK EndAction = 3 // commit if this Repo call's own error_code is empty, else rollback
)

// Enum value maps for EndAction.
var (
	EndAction_name = map[int32]string{
		0: "END_ACTION_UNSPECIFIED",
		1: "END_ACTION_ROLLBACK",
		2: "END_ACTION_COMMIT",
		3: "END_ACTION_COMMIT_IF_OK",
	}
	EndAction_value = map[string]int32{
		"END_ACTION_UNSPECIFIED":  0,
		"END_ACTION_ROLLBACK":     1,
		"END_ACTION_COMMIT":       2,
		"END_ACTION_COMMIT_IF_OK": 3,
	}
)

func (x EndAction) Enum() *EndAction {
	p := new(EndAction)
	*p = x
	return p
}

func (x EndAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_repo_proto_enumTypes[1].Descriptor()
}

func (EndAction) Type() protoreflect.EnumType {
	return &file_proto_repo_proto_enumTypes[1]
}

func (x EndAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndAction.Descriptor instead.
func (EndAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{1}
}

// ModelField is a raw structural description of one field - it reports
// what the client's Go type looks like, not what that shape means.
// Relation-ness, has-many vs belongs-to, and the join tag's two
// comma-separated segments are all interpreted server-side (see
// gist-server/services/gist-mysql-client/model.go's modelFromWire), not here.
type ModelField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                          // "db" tag - the column name
	JsonName      string                 `protobuf:"bytes,2,opt,name=json_name,json=jsonName,proto3" json:"json_name,omitempty"`  // "json" tag
	JoinTag       string                 `protobuf:"bytes,3,opt,name=join_tag,json=joinTag,proto3" json:"join_tag,omitempty"`     // raw "join" tag value, unparsed - empty if absent
	IsSlice       bool                   `protobuf:"varint,4,opt,name=is_slice,json=isSlice,proto3" json:"is_slice,omitempty"`    // Go field is a slice (excluding []byte)
	IsStruct      bool                   `protobuf:"varint,5,opt,name=is_struct,json=isStruct,proto3" json:"is_struct,omitempty"` // element type (or field type if not a slice) is a struct
	Nested        *ModelSchema           `protobuf:"bytes,6,opt,name=nested,proto3" json:"nested,omitempty"`                      // set when is_struct is true
	IsBool        bool                   `protobuf:"varint,7,opt,name=is_bool,json=isBool,proto3" json:"is_bool,omitempty"`       // scalar field's Go type is bool - lets the server coerce a
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelField) Reset() {
	*x = ModelField{}
	mi := &file_proto_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelField) ProtoMessage() {}

func (x *ModelField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelField.ProtoReflect.Descriptor instead.
func (*ModelField) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{0}
}

func (x *ModelField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelField) GetJsonName() string {
	if x != nil {
		return x.JsonName
	}
	return ""
}

func (x *ModelField) GetJoinTag() string {
	if x != nil {
		return x.JoinTag
	}
	return ""
}

func (x *ModelField) GetIsSlice() bool {
	if x != nil {
		return x.IsSlice
	}
	return false
}

func (x *ModelField) GetIsStruct() bool {
	if x != nil {
		return x.IsStruct
	}
	return false
}

func (x *ModelField) GetNested() *ModelSchema {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *ModelField) GetIsBool() bool {
	if x != nil {
		return x.IsBool
	}
	return false
}

type ModelSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []string               `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"` // "source" tag, dot-split (schema.table)
	Fields        []*ModelField          `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelSchema) Reset() {
	*x = ModelSchema{}
	mi := &file_proto_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSchema) ProtoMessage() {}

func (x *ModelSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSchema.ProtoReflect.Descriptor instead.
func (*ModelSchema) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{1}
}

func (x *ModelSchema) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ModelSchema) GetFields() []*ModelField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of leaf/and_group/or_group is set - the wire shape of
	// conditions.Conditioner's three real implementations (condition,
	// andConditions, orConditions).
	Leaf          *ConditionLeaf  `protobuf:"bytes,1,opt,name=leaf,proto3" json:"leaf,omitempty"`
	AndGroup      *ConditionGroup `protobuf:"bytes,2,opt,name=and_group,json=andGroup,proto3" json:"and_group,omitempty"`
	OrGroup       *ConditionGroup `protobuf:"bytes,3,opt,name=or_group,json=orGroup,proto3" json:"or_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_proto_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{2}
}

func (x *Condition) GetLeaf() *ConditionLeaf {
	if x != nil {
		return x.Leaf
	}
	return nil
}

func (x *Condition) GetAndGroup() *ConditionGroup {
	if x != nil {
		return x.AndGroup
	}
	return nil
}

func (x *Condition) GetOrGroup() *ConditionGroup {
	if x != nil {
		return x.OrGroup
	}
	return nil
}

type ConditionLeaf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` // one of gist-server/services/gist-mysql-client/operator's keys
	ValueJson     []byte                 `protobuf:"bytes,3,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionLeaf) Reset() {
	*x = ConditionLeaf{}
	mi := &file_proto_repo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionLeaf) ProtoMessage() {}

func (x *ConditionLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionLeaf.ProtoReflect.Descriptor instead.
func (*ConditionLeaf) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{3}
}

func (x *ConditionLeaf) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ConditionLeaf) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ConditionLeaf) GetValueJson() []byte {
	if x != nil {
		return x.ValueJson
	}
	return nil
}

type ConditionGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*Condition           `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionGroup) Reset() {
	*x = ConditionGroup{}
	mi := &file_proto_repo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionGroup) ProtoMessage() {}

func (x *ConditionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionGroup.ProtoReflect.Descriptor instead.
func (*ConditionGroup) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{4}
}

func (x *ConditionGroup) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Descending    bool                   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_proto_repo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{5}
}

func (x *Sort) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Sort) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type QueryOptions struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Conditions []*Condition           `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Sorts      []*Sort                `protobuf:"bytes,2,rep,name=sorts,proto3" json:"sorts,omitempty"`
	Limit      int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset     int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Lock       bool                   `protobuf:"varint,5,opt,name=lock,proto3" json:"lock,omitempty"` // WithLock() - SELECT ... FOR UPDATE
	// WithRelationConditions(relation, ...) - extra WHERE conditions scoped
	// to one named relation's sub-select, keyed by that relation's alias
	// (the same name buildSubSelect/joinAlias would derive server-side).
	RelationConditions map[string]*ConditionGroup `protobuf:"bytes,6,rep,name=relation_conditions,json=relationConditions,proto3" json:"relation_conditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	mi := &file_proto_repo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{6}
}

func (x *QueryOptions) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *QueryOptions) GetSorts() []*Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

func (x *QueryOptions) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryOptions) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryOptions) GetLock() bool {
	if x != nil {
		return x.Lock
	}
	return false
}

func (x *QueryOptions) GetRelationConditions() map[string]*ConditionGroup {
	if x != nil {
		return x.RelationConditions
	}
	return nil
}

type BeginTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,2,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // optional, mirrors NewNamedTransaction/NewNamedReadTransaction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionRequest) Reset() {
	*x = BeginTransactionRequest{}
	mi := &file_proto_repo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionRequest) ProtoMessage() {}

func (x *BeginTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionRequest.ProtoReflect.Descriptor instead.
func (*BeginTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{7}
}

func (x *BeginTransactionRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *BeginTransactionRequest) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *BeginTransactionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BeginTransactionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionHandle string                 `protobuf:"bytes,1,opt,name=transaction_handle,json=transactionHandle,proto3" json:"transaction_handle,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BeginTransactionResponse) Reset() {
	*x = BeginTransactionResponse{}
	mi := &file_proto_repo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionResponse) ProtoMessage() {}

func (x *BeginTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionResponse.ProtoReflect.Descriptor instead.
func (*BeginTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{8}
}

func (x *BeginTransactionResponse) GetTransactionHandle() string {
	if x != nil {
		return x.TransactionHandle
	}
	return ""
}

type TransactionHandle struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionHandle string                 `protobuf:"bytes,1,opt,name=transaction_handle,json=transactionHandle,proto3" json:"transaction_handle,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionHandle) Reset() {
	*x = TransactionHandle{}
	mi := &file_proto_repo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHandle) ProtoMessage() {}

func (x *TransactionHandle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHandle.ProtoReflect.Descriptor instead.
func (*TransactionHandle) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionHandle) GetTransactionHandle() string {
	if x != nil {
		return x.TransactionHandle
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_repo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{10}
}

func (x *Ack) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Ack) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ModelRow is one model's live scalar field values (its "db" tag ->
// value), for Save/Update - the write-path counterpart of ModelSchema,
// which only ever describes shape. Nested has-many/belongs-to relations
// are not included - the write path (unlike Find) does not support
// writing nested relations in one call; see gist-sdk's Save/Update doc
// comments for why that's a deliberate scope decision, not an oversight.
type ModelRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowJson       []byte                 `protobuf:"bytes,1,opt,name=row_json,json=rowJson,proto3" json:"row_json,omitempty"` // JSON object, keyed by column ("db" tag) name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelRow) Reset() {
	*x = ModelRow{}
	mi := &file_proto_repo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRow) ProtoMessage() {}

func (x *ModelRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRow.ProtoReflect.Descriptor instead.
func (*ModelRow) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{11}
}

func (x *ModelRow) GetRowJson() []byte {
	if x != nil {
		return x.RowJson
	}
	return nil
}

// EndTransaction lets the client fold a Commit/Rollback call into the last
// Repo call of a transaction instead of paying for a separate round trip -
// the close-side counterpart of RepoRequest.begin below. Set only when the
// caller knows this is the transaction's final op (gist-sdk's one-shot
// Service-level helpers, as opposed to its Transaction-based API, are the
// only callers that ever set this).
type EndTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        EndAction              `protobuf:"varint,1,opt,name=action,proto3,enum=gist.EndAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndTransaction) Reset() {
	*x = EndTransaction{}
	mi := &file_proto_repo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTransaction) ProtoMessage() {}

func (x *EndTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTransaction.ProtoReflect.Descriptor instead.
func (*EndTransaction) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{12}
}

func (x *EndTransaction) GetAction() EndAction {
	if x != nil {
		return x.Action
	}
	return EndAction_END_ACTION_UNSPECIFIED
}

type RepoRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionHandle string                 `protobuf:"bytes,1,opt,name=transaction_handle,json=transactionHandle,proto3" json:"transaction_handle,omitempty"` // empty means "begin must be set" - see begin below
	Op                RepoOp                 `protobuf:"varint,2,opt,name=op,proto3,enum=gist.RepoOp" json:"op,omitempty"`
	Schema            *ModelSchema           `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Options           *QueryOptions          `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	Rows              []*ModelRow            `protobuf:"bytes,5,rep,name=rows,proto3" json:"rows,omitempty"` // Save/SaveWithReturning: one or more rows to insert; Update/UpdateWithReturning: exactly one row of new values
	// begin lets the client fold a BeginTransaction call into the first Repo
	// call of a transaction instead of paying for a separate round trip - set
	// only when transaction_handle is empty. gist-sdk's Transaction defers
	// the actual BeginTransaction RPC until the first op for exactly this
	// reason (see gist-sdk/services/gist-mysql-client/service.go).
	Begin *BeginTransactionRequest `protobuf:"bytes,6,opt,name=begin,proto3" json:"begin,omitempty"`
	// end, when set, closes the transaction as part of this same call - see
	// EndTransaction above.
	End           *EndTransaction `protobuf:"bytes,7,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoRequest) Reset() {
	*x = RepoRequest{}
	mi := &file_proto_repo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoRequest) ProtoMessage() {}

func (x *RepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoRequest.ProtoReflect.Descriptor instead.
func (*RepoRequest) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{13}
}

func (x *RepoRequest) GetTransactionHandle() string {
	if x != nil {
		return x.TransactionHandle
	}
	return ""
}

func (x *RepoRequest) GetOp() RepoOp {
	if x != nil {
		return x.Op
	}
	return RepoOp_REPO_OP_UNSPECIFIED
}

func (x *RepoRequest) GetSchema() *ModelSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *RepoRequest) GetOptions() *QueryOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *RepoRequest) GetRows() []*ModelRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *RepoRequest) GetBegin() *BeginTransactionRequest {
	if x != nil {
		return x.Begin
	}
	return nil
}

func (x *RepoRequest) GetEnd() *EndTransaction {
	if x != nil {
		return x.End
	}
	return nil
}

type RepoResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RowsJson     [][]byte               `protobuf:"bytes,1,rep,name=rows_json,json=rowsJson,proto3" json:"rows_json,omitempty"`    // one JSON object per result row (Find/FindOne/*WithReturning)
	Count        int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                         // Count's result
	Exists       bool                   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`                       // Exists' result
	ErrorCode    string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // set on failure ("not_found", "multiple_rows", "internal", ...)
	ErrorMessage string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Affected     int64                  `protobuf:"varint,6,opt,name=affected,proto3" json:"affected,omitempty"` // Save/Update/Delete's affected-row count
	// transaction_handle is set only when this call's request carried begin
	// (i.e. it opened a new transaction) AND did not also carry end (a
	// transaction closed by this same call has no handle worth remembering) -
	// the caller must remember it for any further op on the same transaction
	// and for Commit/Rollback, even if error_code is also set (the
	// transaction is still open server-side and still needs closing).
	TransactionHandle string `protobuf:"bytes,7,opt,name=transaction_handle,json=transactionHandle,proto3" json:"transaction_handle,omitempty"`
	// end_error_code/end_error_message report the outcome of this request's
	// end action, separately from error_code/error_message above - a Repo op
	// can succeed while its folded-in Commit/Rollback fails, or vice versa
	// for END_ACTION_COMMIT_IF_OK, and the caller needs to tell the two apart.
	// Both are empty when the request carried no end, or when the end action
	// itself succeeded.
	EndErrorCode    string `protobuf:"bytes,8,opt,name=end_error_code,json=endErrorCode,proto3" json:"end_error_code,omitempty"`
	EndErrorMessage string `protobuf:"bytes,9,opt,name=end_error_message,json=endErrorMessage,proto3" json:"end_error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RepoResponse) Reset() {
	*x = RepoResponse{}
	mi := &file_proto_repo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoResponse) ProtoMessage() {}

func (x *RepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoResponse.ProtoReflect.Descriptor instead.
func (*RepoResponse) Descriptor() ([]byte, []int) {
	return file_proto_repo_proto_rawDescGZIP(), []int{14}
}

func (x *RepoResponse) GetRowsJson() [][]byte {
	if x != nil {
		return x.RowsJson
	}
	return nil
}

func (x *RepoResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RepoResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *RepoResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RepoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RepoResponse) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

func (x *RepoResponse) GetTransactionHandle() string {
	if x != nil {
		return x.TransactionHandle
	}
	return ""
}

func (x *RepoResponse) GetEndErrorCode() string {
	if x != nil {
		return x.EndErrorCode
	}
	return ""
}

func (x *RepoResponse) GetEndErrorMessage() string {
	if x != nil {
		return x.EndErrorMessage
	}
	return ""
}

var File_proto_repo_proto protoreflect.FileDescriptor

const file_proto_repo_proto_rawDesc = "" +
	"\n" +
	"\x10proto/repo.proto\x12\x04gist\"\xd4\x01\n" +
	"\n" +
	"ModelField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tjson_name\x18\x02 \x01(\tR\bjsonName\x12\x19\n" +
	"\bjoin_tag\x18\x03 \x01(\tR\ajoinTag\x12\x19\n" +
	"\bis_slice\x18\x04 \x01(\bR\aisSlice\x12\x1b\n" +
	"\tis_struct\x18\x05 \x01(\bR\bisStruct\x12)\n" +
	"\x06nested\x18\x06 \x01(\v2\x11.gist.ModelSchemaR\x06nested\x12\x17\n" +
	"\ais_bool\x18\a \x01(\bR\x06isBool\"Q\n" +
	"\vModelSchema\x12\x18\n" +
	"\asources\x18\x01 \x03(\tR\asources\x12(\n" +
	"\x06fields\x18\x02 \x03(\v2\x10.gist.ModelFieldR\x06fields\"\x98\x01\n" +
	"\tCondition\x12'\n" +
	"\x04leaf\x18\x01 \x01(\v2\x13.gist.ConditionLeafR\x04leaf\x121\n" +
	"\tand_group\x18\x02 \x01(\v2\x14.gist.ConditionGroupR\bandGroup\x12/\n" +
	"\bor_group\x18\x03 \x01(\v2\x14.gist.ConditionGroupR\aorGroup\"`\n" +
	"\rConditionLeaf\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x1d\n" +
	"\n" +
	"value_json\x18\x03 \x01(\fR\tvalueJson\"A\n" +
	"\x0eConditionGroup\x12/\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x0f.gist.ConditionR\n" +
	"conditions\"@\n" +
	"\x04Sort\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\x1e\n" +
	"\n" +
	"descending\x18\x02 \x01(\bR\n" +
	"descending\"\xdd\x02\n" +
	"\fQueryOptions\x12/\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x0f.gist.ConditionR\n" +
	"conditions\x12 \n" +
	"\x05sorts\x18\x02 \x03(\v2\n" +
	".gist.SortR\x05sorts\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04lock\x18\x05 \x01(\bR\x04lock\x12[\n" +
	"\x13relation_conditions\x18\x06 \x03(\v2*.gist.QueryOptions.RelationConditionsEntryR\x12relationConditions\x1a[\n" +
	"\x17RelationConditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.gist.ConditionGroupR\x05value:\x028\x01\"i\n" +
	"\x17BeginTransactionRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tread_only\x18\x02 \x01(\bR\breadOnly\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"I\n" +
	"\x18BeginTransactionResponse\x12-\n" +
	"\x12transaction_handle\x18\x01 \x01(\tR\x11transactionHandle\"B\n" +
	"\x11TransactionHandle\x12-\n" +
	"\x12transaction_handle\x18\x01 \x01(\tR\x11transactionHandle\"I\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"%\n" +
	"\bModelRow\x12\x19\n" +
	"\brow_json\x18\x01 \x01(\fR\arowJson\"9\n" +
	"\x0eEndTransaction\x12'\n" +
	"\x06action\x18\x01 \x01(\x0e2\x0f.gist.EndActionR\x06action\"\xb4\x02\n" +
	"\vRepoRequest\x12-\n" +
	"\x12transaction_handle\x18\x01 \x01(\tR\x11transactionHandle\x12\x1c\n" +
	"\x02op\x18\x02 \x01(\x0e2\f.gist.RepoOpR\x02op\x12)\n" +
	"\x06schema\x18\x03 \x01(\v2\x11.gist.ModelSchemaR\x06schema\x12,\n" +
	"\aoptions\x18\x04 \x01(\v2\x12.gist.QueryOptionsR\aoptions\x12\"\n" +
	"\x04rows\x18\x05 \x03(\v2\x0e.gist.ModelRowR\x04rows\x123\n" +
	"\x05begin\x18\x06 \x01(\v2\x1d.gist.BeginTransactionRequestR\x05begin\x12&\n" +
	"\x03end\x18\a \x01(\v2\x14.gist.EndTransactionR\x03end\"\xba\x02\n" +
	"\fRepoResponse\x12\x1b\n" +
	"\trows_json\x18\x01 \x03(\fR\browsJson\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\baffected\x18\x06 \x01(\x03R\baffected\x12-\n" +
	"\x12transaction_handle\x18\a \x01(\tR\x11transactionHandle\x12$\n" +
	"\x0eend_error_code\x18\b \x01(\tR\fendErrorCode\x12*\n" +
	"\x11end_error_message\x18\t \x01(\tR\x0fendErrorMessage*\xc1\x01\n" +
	"\x06RepoOp\x12\x17\n" +
	"\x13REPO_OP_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04FIND\x10\x01\x12\f\n" +
	"\bFIND_ONE\x10\x02\x12\t\n" +
	"\x05COUNT\x10\x03\x12\n" +
	"\n" +
	"\x06EXISTS\x10\x04\x12\b\n" +
	"\x04SAVE\x10\x05\x12\x17\n" +
	"\x13SAVE_WITH_RETURNING\x10\x06\x12\n" +
	"\n" +
	"\x06UPDATE\x10\a\x12\x19\n" +
	"\x15UPDATE_WITH_RETURNING\x10\b\x12\n" +
	"\n" +
	"\x06DELETE\x10\t\x12\x19\n" +
	"\x15DELETE_WITH_RETURNING\x10\n" +
	"*t\n" +
	"\tEndAction\x12\x1a\n" +
	"\x16END_ACTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13END_ACTION_ROLLBACK\x10\x01\x12\x15\n" +
	"\x11END_ACTION_COMMIT\x10\x02\x12\x1b\n" +
	"\x17END_ACTION_COMMIT_IF_OK\x10\x03B&Z$github.com/wieoapps/gist/proto;protob\x06proto3"

var (
	file_proto_repo_proto_rawDescOnce sync.Once
	file_proto_repo_proto_rawDescData []byte
)

func file_proto_repo_proto_rawDescGZIP() []byte {
	file_proto_repo_proto_rawDescOnce.Do(func() {
		file_proto_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_repo_proto_rawDesc), len(file_proto_repo_proto_rawDesc)))
	})
	return file_proto_repo_proto_rawDescData
}

var file_proto_repo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_repo_proto_goTypes = []any{
	(RepoOp)(0),                      // 0: gist.RepoOp
	(EndAction)(0),                   // 1: gist.EndAction
	(*ModelField)(nil),               // 2: gist.ModelField
	(*ModelSchema)(nil),              // 3: gist.ModelSchema
	(*Condition)(nil),                // 4: gist.Condition
	(*ConditionLeaf)(nil),            // 5: gist.ConditionLeaf
	(*ConditionGroup)(nil),           // 6: gist.ConditionGroup
	(*Sort)(nil),                     // 7: gist.Sort
	(*QueryOptions)(nil),             // 8: gist.QueryOptions
	(*BeginTransactionRequest)(nil),  // 9: gist.BeginTransactionRequest
	(*BeginTransactionResponse)(nil), // 10: gist.BeginTransactionResponse
	(*TransactionHandle)(nil),        // 11: gist.TransactionHandle
	(*Ack)(nil),                      // 12: gist.Ack
	(*ModelRow)(nil),                 // 13: gist.ModelRow
	(*EndTransaction)(nil),           // 14: gist.EndTransaction
	(*RepoRequest)(nil),              // 15: gist.RepoRequest
	(*RepoResponse)(nil),             // 16: gist.RepoResponse
	nil,                              // 17: gist.QueryOptions.RelationConditionsEntry
}
var file_proto_repo_proto_depIdxs = []int32{
	3,  // 0: gist.ModelField.nested:type_name -> gist.ModelSchema
	2,  // 1: gist.ModelSchema.fields:type_name -> gist.ModelField
	5,  // 2: gist.Condition.leaf:type_name -> gist.ConditionLeaf
	6,  // 3: gist.Condition.and_group:type_name -> gist.ConditionGroup
	6,  // 4: gist.Condition.or_group:type_name -> gist.ConditionGroup
	4,  // 5: gist.ConditionGroup.conditions:type_name -> gist.Condition
	4,  // 6: gist.QueryOptions.conditions:type_name -> gist.Condition
	7,  // 7: gist.QueryOptions.sorts:type_name -> gist.Sort
	17, // 8: gist.QueryOptions.relation_conditions:type_name -> gist.QueryOptions.RelationConditionsEntry
	1,  // 9: gist.EndTransaction.action:type_name -> gist.EndAction
	0,  // 10: gist.RepoRequest.op:type_name -> gist.RepoOp
	3,  // 11: gist.RepoRequest.schema:type_name -> gist.ModelSchema
	8,  // 12: gist.RepoRequest.options:type_name -> gist.QueryOptions
	13, // 13: gist.RepoRequest.rows:type_name -> gist.ModelRow
	9,  // 14: gist.RepoRequest.begin:type_name -> gist.BeginTransactionRequest
	14, // 15: gist.RepoRequest.end:type_name -> gist.EndTransaction
	6,  // 16: gist.QueryOptions.RelationConditionsEntry.value:type_name -> gist.ConditionGroup
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_repo_proto_init() }
func file_proto_repo_proto_init() {
	if File_proto_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_repo_proto_rawDesc), len(file_proto_repo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_repo_proto_goTypes,
		DependencyIndexes: file_proto_repo_proto_depIdxs,
		EnumInfos:         file_proto_repo_proto_enumTypes,
		MessageInfos:      file_proto_repo_proto_msgTypes,
	}.Build()
	File_proto_repo_proto = out.File
	file_proto_repo_proto_goTypes = nil
	file_proto_repo_proto_depIdxs = nil
}
