// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/statemachine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StateMachineService is gist-server's own service (not part of
// CallbackService - this is customer-to-gist-server, the mirror
// direction) for actually attempting a transition. current_state empty
// means "unset" - gist-server applies the configured initial state,
// exactly like the original's Transition/newMachine's external-storage
// getter does. There is no callback into the customer's process here:
// Transition is a pure "is trigger permitted from current_state, and if
// so what's the new state" check against the configured transition
// graph - everything before and after calling Transition (fetching the
// object, mutating it, persisting it, any other side effect) is
// ordinary code the customer writes themselves.
type TransitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Trigger       string                 `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	CurrentState  string                 `protobuf:"bytes,3,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionRequest) Reset() {
	*x = TransitionRequest{}
	mi := &file_proto_statemachine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionRequest) ProtoMessage() {}

func (x *TransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statemachine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionRequest.ProtoReflect.Descriptor instead.
func (*TransitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_statemachine_proto_rawDescGZIP(), []int{0}
}

func (x *TransitionRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *TransitionRequest) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *TransitionRequest) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

type TransitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewState      string                 `protobuf:"bytes,1,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionResponse) Reset() {
	*x = TransitionResponse{}
	mi := &file_proto_statemachine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionResponse) ProtoMessage() {}

func (x *TransitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statemachine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionResponse.ProtoReflect.Descriptor instead.
func (*TransitionResponse) Descriptor() ([]byte, []int) {
	return file_proto_statemachine_proto_rawDescGZIP(), []int{1}
}

func (x *TransitionResponse) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

func (x *TransitionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TransitionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GraphRequest asks for the graph representation of service_id's
// configured transition graph - purely structural, seeded with that
// service's own configured initial state. It does not reflect any
// particular object's current state, since gist-server holds none (see
// statemachine.proto's own top-level doc comment on why: the caller
// always owns and sends its current state).
//
// implemented_triggers is the caller's own list of trigger names it has
// actually registered a handler for (via giststatemachine.Attach) -
// gist-server has no visibility into that on its own, since Attach runs
// entirely in the caller's process. Any configured trigger not in this
// list gets a "🚧 " prefix in both dot and svg, the same "unimplemented"
// convention gist-api-server's own docs already use for an endpoint
// with no registered handler.
type GraphRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceId           string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ImplementedTriggers []string               `protobuf:"bytes,2,rep,name=implemented_triggers,json=implementedTriggers,proto3" json:"implemented_triggers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GraphRequest) Reset() {
	*x = GraphRequest{}
	mi := &file_proto_statemachine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRequest) ProtoMessage() {}

func (x *GraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statemachine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRequest.ProtoReflect.Descriptor instead.
func (*GraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_statemachine_proto_rawDescGZIP(), []int{2}
}

func (x *GraphRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GraphRequest) GetImplementedTriggers() []string {
	if x != nil {
		return x.ImplementedTriggers
	}
	return nil
}

type GraphResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Dot   string                 `protobuf:"bytes,1,opt,name=dot,proto3" json:"dot,omitempty"`
	// svg is a self-contained, hand-rendered SVG diagram of the same
	// graph - no external Graphviz/layout engine needed to view it, just
	// an SVG-capable viewer (any browser).
	Svg           string `protobuf:"bytes,2,opt,name=svg,proto3" json:"svg,omitempty"`
	ErrorCode     string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphResponse) Reset() {
	*x = GraphResponse{}
	mi := &file_proto_statemachine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphResponse) ProtoMessage() {}

func (x *GraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statemachine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphResponse.ProtoReflect.Descriptor instead.
func (*GraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_statemachine_proto_rawDescGZIP(), []int{3}
}

func (x *GraphResponse) GetDot() string {
	if x != nil {
		return x.Dot
	}
	return ""
}

func (x *GraphResponse) GetSvg() string {
	if x != nil {
		return x.Svg
	}
	return ""
}

func (x *GraphResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GraphResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_statemachine_proto protoreflect.FileDescriptor

const file_proto_statemachine_proto_rawDesc = "" +
	"\n" +
	"\x18proto/statemachine.proto\x12\x04gist\"q\n" +
	"\x11TransitionRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\x12#\n" +
	"\rcurrent_state\x18\x03 \x01(\tR\fcurrentState\"u\n" +
	"\x12TransitionResponse\x12\x1b\n" +
	"\tnew_state\x18\x01 \x01(\tR\bnewState\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"`\n" +
	"\fGraphRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x121\n" +
	"\x14implemented_triggers\x18\x02 \x03(\tR\x13implementedTriggers\"w\n" +
	"\rGraphResponse\x12\x10\n" +
	"\x03dot\x18\x01 \x01(\tR\x03dot\x12\x10\n" +
	"\x03svg\x18\x02 \x01(\tR\x03svg\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2\x88\x01\n" +
	"\x13StateMachineService\x12?\n" +
	"\n" +
	"Transition\x12\x17.gist.TransitionRequest\x1a\x18.gist.TransitionResponse\x120\n" +
	"\x05Graph\x12\x12.gist.GraphRequest\x1a\x13.gist.GraphResponseB&Z$github.com/wieoapps/gist/proto;protob\x06proto3"

var (
	file_proto_statemachine_proto_rawDescOnce sync.Once
	file_proto_statemachine_proto_rawDescData []byte
)

func file_proto_statemachine_proto_rawDescGZIP() []byte {
	file_proto_statemachine_proto_rawDescOnce.Do(func() {
		file_proto_statemachine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_statemachine_proto_rawDesc), len(file_proto_statemachine_proto_rawDesc)))
	})
	return file_proto_statemachine_proto_rawDescData
}

var file_proto_statemachine_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_statemachine_proto_goTypes = []any{
	(*TransitionRequest)(nil),  // 0: gist.TransitionRequest
	(*TransitionResponse)(nil), // 1: gist.TransitionResponse
	(*GraphRequest)(nil),       // 2: gist.GraphRequest
	(*GraphResponse)(nil),      // 3: gist.GraphResponse
}
var file_proto_statemachine_proto_depIdxs = []int32{
	0, // 0: gist.StateMachineService.Transition:input_type -> gist.TransitionRequest
	2, // 1: gist.StateMachineService.Graph:input_type -> gist.GraphRequest
	1, // 2: gist.StateMachineService.Transition:output_type -> gist.TransitionResponse
	3, // 3: gist.StateMachineService.Graph:output_type -> gist.GraphResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_statemachine_proto_init() }
func file_proto_statemachine_proto_init() {
	if File_proto_statemachine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_statemachine_proto_rawDesc), len(file_proto_statemachine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_statemachine_proto_goTypes,
		DependencyIndexes: file_proto_statemachine_proto_depIdxs,
		MessageInfos:      file_proto_statemachine_proto_msgTypes,
	}.Build()
	File_proto_statemachine_proto = out.File
	file_proto_statemachine_proto_goTypes = nil
	file_proto_statemachine_proto_depIdxs = nil
}
