// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/statemachine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StateMachineService_Transition_FullMethodName     = "/gist.StateMachineService/Transition"
	StateMachineService_Graph_FullMethodName          = "/gist.StateMachineService/Graph"
	StateMachineService_MultiLaneGraph_FullMethodName = "/gist.StateMachineService/MultiLaneGraph"
)

// StateMachineServiceClient is the client API for StateMachineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateMachineServiceClient interface {
	Transition(ctx context.Context, in *TransitionRequest, opts ...grpc.CallOption) (*TransitionResponse, error)
	Graph(ctx context.Context, in *GraphRequest, opts ...grpc.CallOption) (*GraphResponse, error)
	MultiLaneGraph(ctx context.Context, in *MultiLaneGraphRequest, opts ...grpc.CallOption) (*MultiLaneGraphResponse, error)
}

type stateMachineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateMachineServiceClient(cc grpc.ClientConnInterface) StateMachineServiceClient {
	return &stateMachineServiceClient{cc}
}

func (c *stateMachineServiceClient) Transition(ctx context.Context, in *TransitionRequest, opts ...grpc.CallOption) (*TransitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionResponse)
	err := c.cc.Invoke(ctx, StateMachineService_Transition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateMachineServiceClient) Graph(ctx context.Context, in *GraphRequest, opts ...grpc.CallOption) (*GraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphResponse)
	err := c.cc.Invoke(ctx, StateMachineService_Graph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateMachineServiceClient) MultiLaneGraph(ctx context.Context, in *MultiLaneGraphRequest, opts ...grpc.CallOption) (*MultiLaneGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiLaneGraphResponse)
	err := c.cc.Invoke(ctx, StateMachineService_MultiLaneGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateMachineServiceServer is the server API for StateMachineService service.
// All implementations must embed UnimplementedStateMachineServiceServer
// for forward compatibility.
type StateMachineServiceServer interface {
	Transition(context.Context, *TransitionRequest) (*TransitionResponse, error)
	Graph(context.Context, *GraphRequest) (*GraphResponse, error)
	MultiLaneGraph(context.Context, *MultiLaneGraphRequest) (*MultiLaneGraphResponse, error)
	mustEmbedUnimplementedStateMachineServiceServer()
}

// UnimplementedStateMachineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateMachineServiceServer struct{}

func (UnimplementedStateMachineServiceServer) Transition(context.Context, *TransitionRequest) (*TransitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transition not implemented")
}
func (UnimplementedStateMachineServiceServer) Graph(context.Context, *GraphRequest) (*GraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Graph not implemented")
}
func (UnimplementedStateMachineServiceServer) MultiLaneGraph(context.Context, *MultiLaneGraphRequest) (*MultiLaneGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MultiLaneGraph not implemented")
}
func (UnimplementedStateMachineServiceServer) mustEmbedUnimplementedStateMachineServiceServer() {}
func (UnimplementedStateMachineServiceServer) testEmbeddedByValue()                             {}

// UnsafeStateMachineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateMachineServiceServer will
// result in compilation errors.
type UnsafeStateMachineServiceServer interface {
	mustEmbedUnimplementedStateMachineServiceServer()
}

func RegisterStateMachineServiceServer(s grpc.ServiceRegistrar, srv StateMachineServiceServer) {
	// If the following call panics, it indicates UnimplementedStateMachineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateMachineService_ServiceDesc, srv)
}

func _StateMachineService_Transition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateMachineServiceServer).Transition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateMachineService_Transition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateMachineServiceServer).Transition(ctx, req.(*TransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateMachineService_Graph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateMachineServiceServer).Graph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateMachineService_Graph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateMachineServiceServer).Graph(ctx, req.(*GraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateMachineService_MultiLaneGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiLaneGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateMachineServiceServer).MultiLaneGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateMachineService_MultiLaneGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateMachineServiceServer).MultiLaneGraph(ctx, req.(*MultiLaneGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StateMachineService_ServiceDesc is the grpc.ServiceDesc for StateMachineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateMachineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gist.StateMachineService",
	HandlerType: (*StateMachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transition",
			Handler:    _StateMachineService_Transition_Handler,
		},
		{
			MethodName: "Graph",
			Handler:    _StateMachineService_Graph_Handler,
		},
		{
			MethodName: "MultiLaneGraph",
			Handler:    _StateMachineService_MultiLaneGraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/statemachine.proto",
}
